### ISSUE TITLE
Session set item looks case sensetive

### ISSUE THREAD

**Issue by gubenkoved** [Azure/aspnet-redis-providers#10]
In nutshell, it looks like assigning Session by some "key" looks case-sensitive, so that it can be resulted in not empty Session after Session.Clear().

I've described issue in details here: http://stackoverflow.com/questions/32955349/redis-session-state-provider-feature-or-bug.

![a267n](https://cloud.githubusercontent.com/assets/1703169/10315569/c22a2b36-6c63-11e5-9b19-3d97fef87c60.png)

**Comment by SiddharthChatrolaMs** [comment]
This is fixed in https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/2.2.1. Thanks for reporting the issue
