### ISSUE TITLE
StackExchange.Redis.StrongName is discontinued

### ISSUE THREAD

**Issue by kim3er** [Azure/aspnet-redis-providers#107]
Hi,

StackExchange.Redis.StrongName is being discontinued in favour of StackExchange.Redis, which is now strong named by default. This change has happened as part of release 2.0.495, which also contains a bug fix that I'm after.

Do you have any plans to release a new version of RedisSessionStateProvider with the new reference?

More info can be found here:
https://github.com/StackExchange/StackExchange.Redis/issues/915

**Comment by SiddharthChatrolaMs** [comment]
@kim3er I will try to change dependency and create new package. If everything runs fine without issue then I should be able to release a new  package sometime in next week.

**Comment by kim3er** [comment]
Thanks @SiddharthChatrolaMs, that's fantastic news!

**Comment by JonCole** [comment]
Given the number of big changes in StackExchange.Redis 2.0, we will likely release this updated package 1) with an incremented major version number and 2) as a preview package until we have done our own perf/stress testing of the change.

**Comment by wjchristenson2** [comment]
Both the RedisOutputCacheProvider and the RedisSessionStateProvider are affected by this. I assume both will be updated next week with a preview flavor right? - not just the RedisSessionStateProvider?

**Comment by JonCole** [comment]
@wjchristenson2 Yes, both will have a new package available.

**Comment by ghd258** [comment]
When will it be released?

**Comment by JonCole** [comment]
Sorry for the delay - we decided we wanted to run some level of stress testing before we felt comfortable releasing anything.  We have now completed that stress testing and it looks to be quite stable at this point.  

We had been hoping to do some perf testing, but we will go ahead and release the pre-release build as soon as possible (hopefully today) given the level of interest in getting access to it.

**Comment by Krashlog** [comment]
Thanks for the heads up, I'm having the exact same issue as @kim3er, our redis client count goes in the 10s of  thousands, we have to recycle our app pool every week or so. We're hoping this is fixed in the 2.x release of StackExchange.Redis.

**Comment by SiddharthChatrolaMs** [comment]
New packages are available now:
https://www.nuget.org/packages/Microsoft.Web.RedisOutputCacheProvider/3.0.0-preview
https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/4.0.0-preview

**Comment by kim3er** [comment]
Thank you for getting the release out, @SiddharthChatrolaMs (and team), we have now integrated new version.

**Comment by Sacrelicious** [comment]
@SiddharthChatrolaMs @JonCole Is there a timeline for getting a non-preview version of this fix released? Thanks

**Comment by SiddharthChatrolaMs** [comment]
Non-preview version of this release are out now.

https://www.nuget.org/packages/Microsoft.Web.RedisOutputCacheProvider/3.0.1
https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/4.0.1
