### ISSUE TITLE
Storing accesskey in KeyVault

### ISSUE THREAD

**Issue by paulhickman-a365** [Azure/aspnet-redis-providers#108]
Is it possible to inject the access key through code rather than in the web.config file so that the key can be stored in Azure Keyvault instead of being embedded in the configuration file?

**Comment by JonCole** [comment]
There is a configuration option that allows you to specify the name of a class and method that can be used to provide the configuration string that the providers use, including the access keys.  You should be able to use that existing extensibility point as a mechanism to inject values from KV.  

https://github.com/Azure/aspnet-redis-providers/wiki/Configuration#settingsclassname-string

**Comment by rtroupin** [comment]
You can override any web config value by setting it in application settings in Azure for the website or deployment slot.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
