### ISSUE TITLE
Introduce support for Session_End event using Redis Keyspace Notifications feature.

### ISSUE THREAD

**Issue by olegburov** [Azure/aspnet-redis-providers#11]
The Redis Cache supports the [Redis Keyspace Notifications](http://redis.io/topics/notifications) feature starting from version 2.8.0, which is used by [Azure Redis Cache](https://azure.microsoft.com/en-us/blog/azure-redis-cache-updates-for-june-2015/) service. Now clients can subscribe on Expired events (events generated every time a key expires) to be notified when an entry is expired.

It would be handy if the `Microsoft.Web.RedisSessionStateProvider` supported the `Session_End` event, using the `Redis Keyspace Notifications` feature.

**Comment by bernardobrezende** [comment]
+1

Digging into this issue I've found this [question at SA](http://stackoverflow.com/questions/23180765/redis-keyspace-notifications-with-stackexchange-redis). 

I've tried to subscribe expire events on `Session_Start` event so I can simulate a `Session_End` behavior. I had no success, it even called my callback action when Redis expired the session keys.

```csharp
protected void Session_Start(object sender, EventArgs e)
{
    using (ConnectionMultiplexer connection = ConnectionMultiplexer.Connect("localhost"))
    {
        IDatabase db = connection.GetDatabase();
        ISubscriber subscriber = connection.GetSubscriber();

        subscriber.Subscribe("__keyevent@0__:*", (channel, value) =>
        {
            // This code never gets called
            System.Diagnostics.Debug.WriteLine("Subscribed!");
        });
    }
}
```

Any thoughts in an alternative solution?

**Comment by SiddharthChatrolaMs** [comment]
There are few complications in supporting Session_End. In case of multiple web roles which role should execute Session_End method etc.

**Comment by SiddharthChatrolaMs** [comment]
Reopen this issue if you are not satisfied with above explanation
