### ISSUE TITLE
Setting up RedisSessionStateProvider using code (Eg start.cs)

### ISSUE THREAD

**Issue by wmmihaa** [Azure/aspnet-redis-providers#114]
We have a scenario where we're using CI to deploy our site to many instances, each using different redis instances. We could manage the RedisSessionStateProvider settings in the web-*.config using transform to set the RedisSessionStateProvider instance.
However, today we only use appSettings and conncectionString as these can be manage per site level in the Azure portal.
I was therefor wondering if it's possible to setup the RedisSessionStateProvider from the Startup::Configuration methods or similar, such that I can set it up using parameters stored in AppSettings?

We're using ASP.Net 4.62 and Microsoft.Web.RedisSessionStateProvider 2.2.6
Cheers
Mikael

**Comment by chunliu** [comment]
The settings of RedisSessionStateProvider can be configured with appSettings keys, and the actual value can be in appSettings. See the wiki [here](https://github.com/Azure/aspnet-redis-providers/wiki/Configuration).

**Comment by mapalan** [comment]
Is this still something that you would like to see? Apologies for the incredibly long response time, I'm relatively new and the rest of our team hasn't had time to update the repo in quite a while.

**Comment by dmorganb** [comment]
We have an scenario where we store the Redis credentials in a KeyVault, so we need to load them in code and create the Redis connection there. This cannot be done (as far as I know) with the web.config configuration.

**Comment by mapalan** [comment]
Thanks for the update. I'll be closing this issue unless there are any further considerations that need to be made.
