### ISSUE TITLE
RedisCacheOutputProvider 3.0.1 doesn't work with non-Azure Redis

### ISSUE THREAD

**Issue by jamesshin83** [Azure/aspnet-redis-providers#116]
I'm not sure if it is to do with being non-Azure Redis but when I try to use RedisOutputCahceProvider on non-Azure redis, it did not store the Output Cache at all.
(Even with https://github.com/Azure/aspnet-redis-providers/issues/115)

I had to downgrade to 1.7.5 to get it to work.

My config was:

`<add name="MyRedisOutputCache" type="Microsoft.Web.Redis.RedisOutputCacheProvider,Microsoft.Web.RedisOutputCacheProvider" applicationName="OutputCacheName" host="server" port="6161" ssl="false" accessKey="RedisPassword" connectionTimeoutInMilliseconds="10000" operationTimeoutInMilliseconds="2000" />`

**Comment by mesuttalebi** [comment]
Same issue here, 
removing these line from modules in asp.net mvc's web config, solved problem for me:

<remove name="OutputCache" />
      <add name="OutputCache" type="Microsoft.AspNet.OutputCache.OutputCacheModuleAsync, Microsoft.AspNet.OutputCache.OutputCacheModuleAsync, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" preCondition="integratedMode" />

**Comment by mapalan** [comment]
Is this an issue you're still having? Apologies for the incredibly long response time, I'm relatively new and the rest of our team hasn't had time to update the repo in quite a while.

**Comment by mapalan** [comment]
Closing due to lack of feedback/reproducibility
