### ISSUE TITLE
Using ASP.NET_SessionId as Redis Key poses a security risk

### ISSUE THREAD

**Issue by mvdzwaan** [Azure/aspnet-redis-providers#117]
Currently the actual ASP.Net SessionID value is used to create the Redis keys. This means that a list of session id's is available outside the ASP.NET domain. The administrator of the Redis Cache is therefor able to hijack ASP.Net Sessions

Would it be possible to just hash(sha256) the SessionID and use this as the key for Redis?

**Comment by mapalan** [comment]
Is this still something you would like to see changed? I think this is a good idea that I'll look into implementing. 

Apologies for the incredibly long response time, I'm relatively new and the rest of our team hasn't had time to update the repo in quite a while.

**Comment by mvdzwaan** [comment]
I would activate that right away. I think it's a very small patch..

I was using Azure Redis and using the console I could see all session ID's, and when I used F12 to change my cookie I was able to login as another user.

**Comment by mapalan** [comment]
Hi @mvdzwaan, I talked to a few people working asp.net core to understand how they manage session data. Session data there is stored in a cache using the session key directly, implying that the cache is a trusted source. We'll be following them on this issue.

**Comment by mapalan** [comment]
I had a quick conversation with the asp.net core team on how they manage session data. My understanding is that the cache is seen a trusted source, and they use session keys directly when interacting with the cache. Given this, I don't think it's necessary to change the default behavior of the session state provider.
