### ISSUE TITLE
Logging Extensiblity

### ISSUE THREAD

**Issue by brendonparker** [Azure/aspnet-redis-providers#118]
The logging mechanism seems a bit limiting. You have to provide a `TextWriter`. This seems heavy if I'm trying to wire it up to a an existing logging framework, for example. Log4Net.

The current methodolgy requires a static method that returns a `TextWriter`, like:
```
public static TextWriter CreateLogger() { }
```

Would it be acceptable to do something like this instead?

``` 
public static Action<DateTime, string, string> CreateLogger() { }
```
Where the args are timestamp, level, and message. That would be easier to implement IMO. 

I'm not sure on the best way to build an adapter using the `TextWriter` when using a logging framework.

I'm thinking something like this, but seems problematic:

```
using log4net;
using System.IO;
using System.Text;

public class RedisLogger : TextWriter
{
    private readonly ILog log;

    public RedisLogger()
    {
        log = LogManager.GetLogger(typeof(RedisLogger));
    }

    public override Encoding Encoding => Encoding.UTF8;

    public static TextWriter Log()
    {
        return new RedisLogger();
    }
    // This is the method the LogUtility is invoking.
    // This TextWriter implementation doesn't care about the other methods.
    // arg0 is the DateTime timestamp
    // arg1 is the string logLevel
    // arg2 is the string logMessage    
    public override void WriteLine(string format, object arg0, object arg1, object arg2)
    {
        // Naive casts, but for sample purposes...
        Log(arg1 as string, arg2 as string);
    }

    private void Log(string level, string message)
    {
        switch(level)
        {
            case "[Error]":
                log.Error(message);
                break;
            case "[Info]":
            default:
                log.Info(message);
                break;
        }
    }
}
```

I'm happy to make a PR if its agreeable. Otherwise, can I get further confirmation/guidance on the current `TextWriter` approach.

**Comment by mapalan** [comment]
For simplicity's sake, I would prefer if you used the `TextWriter` approach. Is this an issue you're still working on or would like to see updated?
Apologies for the incredibly long response time, I'm relatively new and the rest of our team hasn't had time to update the repo in quite a while.

**Comment by brendonparker** [comment]
I was able to work around it, by writing a class that derrives from `TextWriter` (see above). 

Just felt hacky. I don't really like having to Subclass `TextWriter`. 

What I have will work fine, unless this library changes how it is writing to TextWriter so that it hits a different overload of `WriteLine`.

I'm fine if you want to close this issue.

**Comment by mapalan** [comment]
Thanks for the update. There aren't plans to change anything with respect to this, so I'll go ahead and close the issue.
