### ISSUE TITLE
Creating new provider but methods involving session id not executing

### ISSUE THREAD

**Issue by hoagsie** [Azure/aspnet-redis-providers#119]
Repo: https://github.com/hoagsie/customsessionprovider

Under `MySessionProvider`, I've created a class inheriting from `SessionStateStoreProviderAsyncBase`. However, none of the methods that accept a sessionId are getting called including

- CreateUninitializedItemAsync
- GetItemAsync
- GetItemExclusiveAsync
- ReleaseItemExclusiveAsync
- RemoveItemAsync
- ResetItemTimeoutAsync
- SetAndReleaseItemExclusiveAsync

This doesn't let me see the sessionId and severely hinders what I can do. How do I get these to hook and fire?

I've ran my solution with IIS Express and Full.

**Comment by mapalan** [comment]
This does not seem relevant to this repo's session state provider. Are you still having an issue with this?

**Comment by mapalan** [comment]
This does not seem relevant to the redis provider.
