### ISSUE TITLE
Web.config file not updated when installing Microsoft.Web.RedisSessionStateProvider

### ISSUE THREAD

**Issue by schellem** [Azure/aspnet-redis-providers#120]
After adding package in VS2017 readme.txt is opened saying my web.config was updated but it is not. The lack of documentation does not help me figure what entries I need to add manually.

**Comment by aravindyeduvaka** [comment]
https://github.com/Azure/aspnet-redis-providers/wiki/Configuration This should help you add the required config manually. 
Have you been able to reproduce this issue again?

**Comment by schellem** [comment]
Thanks for the doc link, however, this always occurs with our project I have not tried to reproduce from a new project. I suspect it might be related to the fact that our project is quite old, it originated from the ASPX days. It seems the only thing that fails is the web.config update so not a terrible issue if you know what to add. I finally saw the web.config.transform in the package.

The bad part I guess is the silent failure. Something else that may give you a hint as to the issue is that I had to add below entry to the web.config as well, it is not included in the transform. I don't remember the error

<remove name="Session"/>
        <add name="Session" type="Microsoft.AspNet.SessionState.SessionStateModuleAsync, Microsoft.AspNet.SessionState.SessionStateModule, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" preCondition="integratedMode"/>

**Comment by mapalan** [comment]
Is this an issue you are still seeing or can reproduce? Apologies for the incredibly long response time, I'm relatively new and the rest of our team hasn't had time to update the repo in quite a while.

**Comment by schellem** [comment]
And I don’t have time to go back and test stuff for Microsoft.

**Comment by mapalan** [comment]
It's quite understandable if you don't have the time to help reproduce an error from over a year ago, however, I can't seem to reproduce this error. Creating a new, empty ASP.NET Web Application, the line that you needed to manually add was automatically added to web.config after installing the NuGet package, as it should have been after the installation of the Microsoft.Web.SessionStateProviderAsync dependency as noted [here](https://devblogs.microsoft.com/aspnet/introducing-the-asp-net-async-sessionstate-module/) (point 2 under "How to use the Async SessionState module").

**Comment by mapalan** [comment]
Closing due to lack of feedback and reproducibility

**Comment by augustarosie** [comment]
> Is this an issue you are still seeing or can reproduce? Apologies for the incredibly long response time, I'm relatively new and the rest of our team hasn't had time to update the repo in quite a while.

Would you like to collab, Mr. Palaniappan ?
