### ISSUE TITLE
Error: Provider must implement the class 'System.Web.SessionState.SessionStateStoreProviderBase'.

### ISSUE THREAD

**Issue by kunjan13** [Azure/aspnet-redis-providers#123]
For me the issue is as it says in the configuration in below line:

 ```
<add name="Session"
         type="Microsoft.AspNet.SessionState.SessionStateModuleAsync, Microsoft.AspNet.SessionState.SessionStateModule, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
         preCondition="integratedMode" />
```

does it only supports "integratedMode"? My app is hosted on "classic" app pool. I tried with classic app pool and it gives me same error:
"Provider must implement the class 'System.Web.SessionState.SessionStateStoreProviderBase'".

**Comment by aravindyeduvaka** [comment]
Can you verify if this is the same issue as https://github.com/Azure/aspnet-redis-providers/issues/99

**Comment by kunjan13** [comment]
I have verified issue #99 this is same but in this case we have asp.net application app pool using classic mode and not integrated mode as it says in above configuration

So my question is does rediscachesessionstate provider support classic mode of application pool?

**Comment by samuel-knutson** [comment]
Any update on this issue? I'm facing the same problem. I got the redis session state provider working in a new standalone project, but having trouble integrating it with an existing application that is hosted in a  classic IIS app pool

**Comment by mapalan** [comment]
I don't think we plan to support classic pools at this time, but if it's something that many people in the community want, we can look into it. From what I've read up on classic pools, [you should only add an application to an application pool in Classic mode if the application fails to work in Integrated mode](https://docs.microsoft.com/en-us/iis/get-started/introduction-to-iis/introduction-to-iis-architecture#classic-application-pool-mode).

Apologies for the incredibly long response time, I'm relatively new and the rest of our team hasn't had time to update the repo in quite a while.

**Comment by samuel-knutson** [comment]
I migrated my project to an Integrated app pool, so I no longer have this requirement.

**Comment by mapalan** [comment]
Thanks for the update. I'll be closing this issue then.
