### ISSUE TITLE
Redis Null should be part of internal Serialize method instead of BS

### ISSUE THREAD

**Issue by marafiq** [Azure/aspnet-redis-providers#125]
https://github.com/Azure/aspnet-redis-providers/blob/b9a5b1d41299d74145f89c2abc466f73cc636e69/src/Shared/BinarySerializer.cs#L17

Redis Null should be part of an internal Serialize method instead of Binary Serializer.
- If you are adding a custom serializer via config, you have to make sure, you return RedsNull not null.
- It adds a dependency on Redis types when serializer is implemented in a separate assembly.

**Comment by mapalan** [comment]
I'll look into this, and hopefully have an update that fixes this soon. Apologies for the incredibly long response time, I'm relatively new and the rest of our team hasn't had time to update the repo in quite a while.

**Comment by mapalan** [comment]
The RedisNull class is internal, meaning that there should be no way to have a dependency on this class from a separate assembly. Also, [there is an example of a separate serializer in the configuration wiki](https://github.com/Azure/aspnet-redis-providers/wiki/Configuration#redisserializertype-string) without a dependency on RedisNull.
Could you look give more details about the issue you're having?

**Comment by marafiq** [comment]
Thanks for change at this point I think there is no need for RedisNull type, it can be removed. I think this commit https://github.com/Azure/aspnet-redis-providers/commit/256e8ff886eb9fb609c737874885da2e8e75f1ab#diff-b843c3b79a632e328c2513b337362452 fixed the issue. As it is not used anywhere now. Commit is checking for null that was not the case before. 
Earlier you can not return null from ``ISerializer.Serialize`` method because implementation was always expecting serlializable type, see if that is still the case. Null should be handled implicitly, or should be documented.

In case someone needs it, my scenario was storing large data sets in Redis because rdlc only support storage in session which was adding latency in redis itself.
public class CompressedRedisSerializer : ISerializer
    {

        public byte[] Serialize(object data)
        {
            if (data == null)
                data = new RedisSerializableNull();//Consumer do not need to do this or it should be documented

            using (var memoryStream = new MemoryStream())
            {
                using (var deflateStream = new DeflateStream(memoryStream, CompressionLevel.Optimal))
                {
                    var binaryFormatter = new BinaryFormatter();
                    binaryFormatter.Serialize(deflateStream, data);
                }

                return memoryStream.ToArray();
            }
        }

        public object Deserialize(byte[] data)
        {
            if (data == null) return null;

            var binaryFormatter = new BinaryFormatter();

            using (var memoryStream = new MemoryStream(data, 0, data.Length))
            {
                using (var deflateStream = new DeflateStream(memoryStream, CompressionMode.Decompress))
                {
                    memoryStream.Seek(0, SeekOrigin.Begin);
                    var deserializedData = binaryFormatter.Deserialize(deflateStream);
                    return deserializedData.GetType() != typeof(RedisSerializableNull) ? deserializedData : null;
                }
            }
        }
    }

Question About BinarySerlializer: Is it secure? Should not it be replaced with more faster serliazer which is faster & can serlize complex type like dataset & other herarichies like rdlc schema.

**Comment by mapalan** [comment]
Is there any reason that you think that the default `BinarySerializer` is insecure? It does not encrypt and decrypt data stored in Redis with a secret key, so I could understand from that point of view if it feels insecure, but I think that `BinarySerializer` is a simple option that works for many applications. Given that it's possible to use a custom `ISerializer`, I don't think it's necessary to change the default from the simple `BinarySerializer`.

**Comment by marafiq** [comment]
CA2300: Do not use insecure deserializer BinaryFormatter
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2300?view=vs-2019
Since this stores data coming from virtually browser in case of rdlc or session data + ~_viewState ( I know its old). 
Note: Replacing it also means that it works with everything you throw at it which might not be case for json serializer

**Comment by mapalan** [comment]
Thanks for bringing this up, I hadn't seen that issue with BinaryFormatter. If we do change the serializer, then any data currently in Redis would be unusable. @JonCole do you have any thoughts on changing the default serializer?

**Comment by JonCole** [comment]
Yes, changing the default serializer would be a breaking change, so we would have to do that with a version bump, clear documentation, etc. if we go that route.  We should have a followup discussion with the .NET security team to get current guidance around this serializer.

**Comment by marafiq** [comment]
Great, thanks. Its slow & allocates more, serializing datatable with 10000 rows - see benchmark below.
Another frustration with using this library is this package "Microsoft.ReportingServices.ReportViewerControl.WebForms" is used to display "rdlc" in .net framework applications. 
Reports produce large data sets & Redis being single threaded, under heavy load it creates all sort of issues. May be its stretch, if you can talk to the team managing "Microsoft.ReportingServices.ReportViewerControl.WebForms" to allow consumers to choose where data will be stored instead of default session state, or may be open source so at least folks can fork it. 

Some benchmark I did a year ago, when scaling 4K concurrent user web app. There are lot of issues with Redis Time Out even in this repo which stems out from large object given Redis is single threaded. Might be helpful. In our case this compression + increasing Redis timeout solve all those intermittent issues.

![image](https://user-images.githubusercontent.com/9109259/82383563-16b52500-99fc-11ea-8405-1ce080c110a7.png)

**Comment by mapalan** [comment]
@marafiq I would suggest using a custom serializer for your needs that is either more space efficient and/or faster at serializing/deserializing data. Given that the original premise of this thread no longer seems to be an issue, I would suggest closing this issue. I have created another issue specifically for BinaryFormatter.

**Comment by marafiq** [comment]
yap that's fair, as original issue is solved. Though RedisNull can be removed since its not being used even internally. But not a concern for consumers.
