### ISSUE TITLE
RedisSessionStateProvider.LastException is never set to null

### ISSUE THREAD

**Issue by maximvsidorenko** [Azure/aspnet-redis-providers#138]
We discovered that the `RedisSessionStateProvider.LastException`, being once set to some value, is never set back to `null` in the scope of the same HTTP request.

The `public static RedisSessionStateProvider.LastException` is set to exception value in cases when an exception is thrown during any Redis provider operation issues.
`RedisSessionStateProvider.LastException` is checked for null in provider methods that change the state, such as `CreateUninitializedItemAsync`, `ResetItemTimeoutAsync`, `RemoveItemAsync`, `ReleaseItemExclusiveAsync`, `SetAndReleaseItemExclusiveAsync`.

I do not see any method that sets `LastException` back to null.

LastException property has the following description:

```
/// <summary>
/// We do not want to throw exception from session state provider because this will break customer application and they can't get chance to handel it.
/// So if exception occurs because of some problem we store it in HttpContext using a key that we know and return null to customer. Now, when customer
/// get null from any of session operation they should call this method to identify if there was any exception and because of that got null.
/// </summary>
```

[Wiki](https://github.com/Azure/aspnet-redis-providers/wiki/Configuration) contains the following note:

> If you set throwOnError to false, then instead of throwing an exception when some error occurs, it will fail silently. If you need to check if there was some error and if there was one, what the exception was, you can check it using static property "Microsoft.Web.Redis.RedisSessionStateProvider.LastException"

So, according to this, a client application is supposed to check this setting.
However, there is no note that a client application is supposed to set `LastException` back to null, after checking its value and handling an exception.

Also, since this setting is specific for the Redis provider, it is hardly checked and set to null by the ASP.NET session module.

As far as I can see, the `LastException` is stored in `HttpContext.Current`, so its value will be null on the next HTTP request.
However, in the scope of the same request, once faced with an exception, the provider is not able to handle any further operations that require changing the session state.

I would consider this a bug.

**Comment by mapalan** [comment]
Hmm, I think that although it wasn't explicitly noted in the wiki, the client application should set `LastException` to `null`. My reasoning is that an exception indicates the session state may not be in a good state for any number of reasons and usually would require a manual intervention from the client application. If the client application deems the error irrelevant, it can set `LastException` to `null` and continue attempting to modifying the session state.

My understanding is that using `LastException` ensures that calling the same function multiple times does not result in the same error over and over again, however, I might be mistaken. Most of the LastException code was committed in the (very first commit)[https://github.com/Azure/aspnet-redis-providers/commit/8f7c34a97f9f13b0aad30e1b22b50dd0e7f9f6c1]. @JonCole might be able to give better insight into this.

**Comment by maximvsidorenko** [comment]
Hi @mapalan, thank you for answering this.

> @JonCole might be able to give better insight into this.

It would be great to hear from the author of an initial commit on the purpose of this.

> Hmm, I think that although it wasn't explicitly noted in the wiki, the client application should set `LastException` to `null`.

Could this information be added to the documentation then?

> My reasoning is that an exception indicates the session state may not be in a good state for any number of reasons and usually would require a manual intervention from the client application. If the client application deems the error irrelevant, it can set LastException to null and continue attempting to modifying the session state.

As far as I understand, the main client of the Redis session state provider is ASP.NET session state module, which is not aware of any specific API of the Redis session state provider, so does not set `LastException` to `null`. Is it expected?

**Comment by Joe-Woodhead-BigChange** [comment]
I'm glad I came across your issue. We are having some significant problems around this area where our write locks are not being released due to LastException being set when it hits RemoveItemAsync. As far as I know we can't set this prior to .NET running AcquireSessionState which happens way before the request actually starts processing

The result of this is all subsequent requests for that session are blocked for the full TTL of the _Write_Lock Redis key and there's no way we can stop it without writing something to manually release that lock. This happens because the RedisTimeoutException thrown by StackExchange.Redis doesn't know if the request is actually still being processed by the Redis server.

@maximvsidorenko What did you do as a workaround to this problem? 

@stanleysmall-microsoft I see you are actively contributing to main. Is this something you are aware of? Is another version of this package being prepared?

**Comment by stanleysmall-microsoft** [comment]
Hello @Joe-Woodhead-BigChange 

I am currently working on a new package release, and I will investigate this issue further.
