### ISSUE TITLE
No connection is available to service this operation: EVAL

### ISSUE THREAD

**Issue by mrcoulson** [Azure/aspnet-redis-providers#140]
I have a web application that runs in a load balanced configuration on two different servers.  I have an Azure Redis cache for session state.  

In my dev environment, this works perfectly.  I created a new cache for this application in my prod environment and pointed my prod environment to this cache.  I get the error "No connection is available to service this operation: EVAL" when I'm trying to run the site.  If I point my dev site at my prod cache, I get the same error.  If I point my prod site at my dev cache, the site works fine.  

So, for some reason, the prod cache is just not working.  As far as I can tell, the caches are the same -- except for the password and name, of course.  I have tried to delete and re-create my prod cache, but I get the same bad result.  It's as if any Redis cache I've created in the last few weeks is not working.  

My application is in ASP.Net 4.5 and I have the Microsoft.Web.RedisSessionStateProvider.dll version 2.2.0.311 on my servers.  

Here is my connection string:

```
<sessionState mode="Custom" customProvider="RedisSessionStateProvider">
  	<providers>
		<add name="RedisSessionStateProvider" type="Microsoft.Web.Redis.RedisSessionStateProvider" connectionString="MyProdCache.redis.cache.windows.net:6380,password=thePasswordIsABunchOfCharacters,ssl=True,abortConnect=False" />
  	</providers>
</sessionState>
```

Is there something I should try adding to my connection string?  Or any other insight?

Thanks!

Jeremy

**Comment by mapalan** [comment]
Hmm that's odd. I found [this thread](https://github.com/StackExchange/StackExchange.Redis/issues/292) with a similar issue. Looking at that thread, my suggestions would be to try using the secondary connection key or regenerating the primary key. I would also suggest updating your provider.

**Comment by mrcoulson** [comment]
@mapalan Interesting.  Changing to the secondary key did not help nor did regenerating the primary.  I believe the version of the provider I'm using, 2.2.3011, is the highest version that can be used with .Net 4.5.  I can't upgrade the framework on the site.  If this is the case, why would it be that the provider won't work for these new caches?  Do caches created after March 2020 have some different requirements than those created earlier?

**Comment by mapalan** [comment]
Is this only an issue you see for caches created after March? In that case, this might be because [the default TLS version is changing to 1.2](https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-remove-tls-10-11#net-framework). Can you try updating your client and seeing if that fixes the issue?

**Comment by mrcoulson** [comment]
Correct.  This site connects a-okay to caches I created previously.  This site is running on Windows Server 2008 R2.  Although settings in the site were set to use TLS 1.2, it looks like Windows Server 2008 R2 only supports 1.0 out of the box.  I updated the registry for the machine to support 1.2 and I now see the server is using 1.2 when I try to access it in Chrome; however, connecting to the Redis cache still fails.

I do notice, however, that Chrome reports outdated connection settings (SHA-1 and AES_256_CBC).  I'm not sure how to fix this.  Do you think this could still be causing Redis connection issues even though the protocol is 1.2?

**Comment by mapalan** [comment]
Oh, by client I meant your website/application. Does your connection string contain the fields `ssl=true` and `sslprotocols=tls12` as recommended [here](https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-remove-tls-10-11#net-framework)?

**Comment by mrcoulson** [comment]
I get the error "Keyword 'sslprotocols' is not supported" when I use that.  I think that sslprotocols was added in a later version than 2.2.  FWIW, an app we have running ASP.Net Core on a Windows 2012 server connects to these Redis caches without difficulty.

**Comment by mapalan** [comment]
Since you're on an older version of the provider that references StackExchange.Redis.StrongName instead of StackExchange.Redis, I would suggest you try [this solution](https://stackoverflow.com/a/60113986).

**Comment by mrcoulson** [comment]
Woo!  I got a new error message :)  I updated Microsoft.Web.RedisSessionStateProvider.dll to version 2.26 (apparently the latest version that works with .Net 4.5) and StackExchange.Redis.StrongName.dll to version 1.21 (apparently the latest version supported by the 2.26 Redis dll) and now I'm getting this message!

No connection is available to service this operation: EVAL; An existing connection was forcibly closed by the remote host; IOCP: (Busy=2,Free=998,Min=2,Max=1000), WORKER: (Busy=1,Free=32766,Min=2,Max=32767), Local-CPU: unavailable

**Comment by mrcoulson** [comment]
> Since you're on an older version of the provider that references StackExchange.Redis.StrongName instead of StackExchange.Redis, I would suggest you try [this solution](https://stackoverflow.com/a/60113986).

I just read this.  I'll try it now.

**Comment by mrcoulson** [comment]
I don't actually have any code in the application that makes any mention of the StackExchange.Redis dll.  I didn't write it, so I definitely don't fully understand it.  The only mention of Redis in any of the code is in the config file entry I added at the beginning of the thread.  I'm not sure how to change the reference to the DLL.

**Comment by mapalan** [comment]
> I get the error "Keyword 'sslprotocols' is not supported" when I use that. I think that sslprotocols was added in a later version than 2.2. FWIW, an app we have running ASP.Net Core on a Windows 2012 server connects to these Redis caches without difficulty.

In your `web.config`, are you using a specific `connectionString` field, or are you using individual fields for `host`, `port`, `accessKey`, etc?

**Comment by mapalan** [comment]
@mrcoulson has there been any update about this issue?

**Comment by lwlwalker** [comment]
Hi @mapalan , thank you for your answers. Adding "sslprotocols=tls12" to my connection string worked for me. 
Thank you!

**Comment by mapalan** [comment]
This seems like a tls issue. see #144 on how to fix
