### ISSUE TITLE
Implement IEnumerable<KeyValuePair<string, object>> in RedisOutputCacheProvider

### ISSUE THREAD

**Issue by alasdair-stark-screenmedia** [Azure/aspnet-redis-providers#141]
We have been working with the DevTrends.MvcDonutCaching package found at https://github.com/moonpyk/mvcdonutcaching

This package has been useful as it allows us to implement Donut caching in MVC and works with RedisOutputCacheProvider.

We have run into an issue with the MvcDonutCaching package when it comes to clearing the cache. In order to use the RemoveItems(...) method, the concrete implementation of OutputCacheProvider must also implement IEnumerable<KeyValuePair<string, object>>. You can see this code in the following file:

https://github.com/moonpyk/mvcdonutcaching/blob/master/DevTrends.MvcDonutCaching/OutputCacheManager.cs - Line 140

This RemoveItems method exists for the case where an action has route parameters and we want a separate cache entry for each combination of parameter values. When we want to clear all cache items for this action, we must get a list of all of the keys in the cache and do some pattern matching to figure out what to delete.

Do you think it is reasonable of the MvcDonutCaching package to expect an OutputCacheProvider to implement this interface? Is it within the scope of this package to do so? Due to the accessibility levels of the classes inside the package, we would currently have to fork the entire repo, make our own modifications and host the package internally to do so. We'd rather avoid that if this could be useful functionality to provide to other consumers of this package.

**Comment by mapalan** [comment]
Hi @alasdair-stark-screenmedia, this seems out of scope for the OutputCacheProvider, which is why I'm leaning towards not implementing this method in this provider.

**Comment by alasdair-stark-screenmedia** [comment]
Fair enough @mapalan, I understand that this repo provides a faithful implementation of OutputCacheProvider.

I think this is really about the limitations of OutputCacheProvider itself. Having no way to retrieve all keys from the cache or get/delete with a wildcard/pattern makes it unusable for us.

I've forked the repo into our own Azure DevOps instance and implemented the changes there for our own use. I'd be happy to share them if you're ever interested.

**Comment by mapalan** [comment]
Thanks for the update.

**Comment by samgooch** [comment]
> Fair enough @mapalan, I understand that this repo provides a faithful implementation of OutputCacheProvider.
> 
> I think this is really about the limitations of OutputCacheProvider itself. Having no way to retrieve all keys from the cache or get/delete with a wildcard/pattern makes it unusable for us.
> 
> I've forked the repo into our own Azure DevOps instance and implemented the changes there for our own use. I'd be happy to share them if you're ever interested.

Are you able to share what you did? I'd like to use the Redis provider AND the MVC Donut Caching package
