### ISSUE TITLE
Session timeouts during peak load

### ISSUE THREAD

**Issue by JljHook** [Azure/aspnet-redis-providers#143]

**Comment by JljHook** [comment]
Hi,
During peak load(900 rpm) we get occasionally bursts of session timeouts.
Error is:
Timeout performing EVAL (1000ms), next: EVAL, inst: 47, qu: 0, qs: 2, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: Unspecified/xxxx.redis.cache.windows.net:6380, mgr: 10 of 10 available, clientName: SvrProdVmWin, IOCP: (Busy=0,Free=1000,Min=400,Max=1000), WORKER: (Busy=67,Free=32700,Min=400,Max=32767), v: 2.0.601.3402 
What we have tried:
- Change default timeout values to: retryTimeoutInMilliseconds="3000" databaseId="0"  connectionTimeoutInMilliseconds="15000" operationTimeoutInMilliseconds="1000"
- Increased thread count in IIS
- Increased Azure VM perf. tier to rule out CPU pressure

**Comment by cdnico** [comment]
Azure vm is on windows? I had similar problems after giving up running iis, I end up creating 3 (master slave slave) redis last version on Linux. Solved my problem.

**Comment by JljHook** [comment]
Yes we are using Azure VM. I've changed now retryTimeoutInMilliseconds to 5000ms and operationtimeout to 6000ms let's see does it have an effect. 
Previously we were using Ncache to manage session, it worked fine and should work in Azure VM as well. It does require service installation to the VM though.

**Comment by mapalan** [comment]
That could happen for any number of reasons, like a failover or a network issue. Were there any long-lasting issues that occurred?

**Comment by JljHook** [comment]
Hi, 
We are still getting timeouts: 
Timeout performing EVAL (6000ms), active: EVAL, next: EVAL, inst: 8, qu: 0, qs: 74, aw: False, rs: CompletePendingMessage, ws: Idle, in: 65536, serverEndpoint: Unspecified/svrprodcache.redis.cache.windows.net:6380, mgr: 9 of 10 available, clientName: SvrProdVmWin, IOCP: (Busy=1,Free=999,Min=400,Max=1000), WORKER: (Busy=144,Free=32623,Min=400,Max=32767), v: 2.0.601.3402 

Looks like no matter how long you set the timeout it still fails eventually..

**Comment by mapalan** [comment]
From that error message, `in: 65536` is quite a lot of data waiting on the client side to be read. This might be because the session data being stored in redis is quite large, which can result in timeouts ([link](https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-troubleshoot-client#large-request-or-response-size)). From the link: the preferred solution is to break up your data into related smaller values.

**Comment by Leonardo-Ferreira** [comment]
@JljHook I'd say that 400 worker threads is quite a lot... as a rule of thumb I set the max for NumberOfCores * 5... depending on the nature of the application, perhaps even a small multiplier is the correct option for you. 
Remember that timeouts can occur AFTER redis has responded: If a worker thread isn't capable of retrieving the result in a timely fashion, despite being 100% the operation will timeout. Having that many threads will cause the processor to switch context more frequently, increasing the time between pick-ups (after getting done with a thread, the CPU will have to switch up to 399 other ones before coming back to the first one)

**Comment by JljHook** [comment]
> 
> 
> @JljHook I'd say that 400 worker threads is quite a lot... as a rule of thumb I set the max for NumberOfCores * 5... depending on the nature of the application, perhaps even a small multiplier is the correct option for you.
> Remember that timeouts can occur AFTER redis has responded: If a worker thread isn't capable of retrieving the result in a timely fashion, despite being 100% the operation will timeout. Having that many threads will cause the processor to switch context more frequently, increasing the time between pick-ups (after getting done with a thread, the CPU will have to switch up to 399 other ones before coming back to the first one)

We have 8Vcores with these settings:
minWorkerThreads = "50"
minIoThreads = "50"
Our application is legacy ASP.net webforms with quite large sessiondata. Should we try let's say with 300 threads instead?

**Comment by Leonardo-Ferreira** [comment]
Theres something wrong there @JljHook! You're saying that you configured to 50 min threads, which I believe is a good number, but your exception is reporting a completely different number! `WORKER: (Busy=144,Free=32623,Min=400,Max=32767)`
First of all I would suggest that you find where/who is making such change!

**Comment by JljHook** [comment]
Hi,
The value specified in this configuration element IS a per-core setting. For example, if you have a 4 core machine and want your minIOThreads setting to be 200 at runtime, you would use <processModel minIoThreads="50"/>. What amount of threads we should try?

**Comment by Leonardo-Ferreira** [comment]
I would start with a minimum value of 5 and a maximum of 10 worker threads per core. On a 8 core machine you would be able to instantaneously "swallow" 40 requests and given pressure, up to 80. If your requests take 500 ms to complete you would work at 80-160 req/sec... I think that's a good start... If the outcomes are not desirable, you should also try to DECREASE the number of worker threads per core.

**Comment by mapalan** [comment]
@JljHook have you seen any improvement with timeouts, or are they continuing to be a pain point?

**Comment by JljHook** [comment]
These settings(minWorkerThreads = "10"
        minIoThreads = "10") cause same issues:
Error 1:
The timeout was reached before the message could be written to the output buffer, and it was not sent, command=EVAL, timeout: 6000, outbound: 93KiB, inbound: 0KiB, next: EVAL, inst: 0, qu: 0, qs: 43, aw: True, rs: ReadAsync, ws: Idle, in: 65536, serverEndpoint: Unspecified/svrprodcache.redis.cache.windows.net:6380, mgr: 10 of 10 available, clientName: SvrProdVmWin, IOCP: (Busy=0,Free=1000,Min=80,Max=1000), WORKER: (Busy=85,Free=32682,Min=80,Max=32767), v: 2.0.601.3402 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
Error 2:
Message: No connection is available to service this operation: EVAL; IOCP: (Busy=0,Free=1000,Min=80,Max=1000), WORKER: (Busy=42,Free=32725,Min=80,Max=32767), Local-CPU: n/a

**Comment by JljHook** [comment]
We decided to rollback using Ncache session provider. Looks like large sessions will cause issues like this.
