### ISSUE TITLE
Can not get access to the redis connection due to ProviderConfiguration being internal

### ISSUE THREAD

**Issue by projecteon** [Azure/aspnet-redis-providers#16]
Hi,

Redis recommends only having one connection per instance. At the current time there is no way to inject an instance, nor collect the instance created by the session handler. One workaround would be access to the ProviderConfiguration and reuse the try get connection code. 

Could you either open this up or give other means of reusing the same connection for an application?

Preferably the ability to inject or presetup the connection so it can be closed on app shutdown as well, as this does not happen today.

**Comment by SiddharthChatrolaMs** [comment]
Are you talking about ability to create connection pool ?

**Comment by SiddharthChatrolaMs** [comment]
This is inactive for a while now so closing it
