### ISSUE TITLE
Allow session provider to use connection string from <connectionStrings> section

### ISSUE THREAD

**Issue by andreymir** [Azure/aspnet-redis-providers#17]
Allow redis session provider to use connection string from `<connectionStrings>` section in `web.config`.

**Comment by ricardopolo** [comment]
:+1:

**Comment by SiddharthChatrolaMs** [comment]
I have this on my list of task. If any of you got time to do it than send pull request.

**Comment by SiddharthChatrolaMs** [comment]
Added comment on pull request

**Comment by SiddharthChatrolaMs** [comment]
NuGet-Release/RedisSessionStateProvider-2.2.0 has this
