### ISSUE TITLE
RedisUtility; Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by DarthSonic** [Azure/aspnet-redis-providers#171]
`at System.Collections.Specialized.NameObjectCollectionBase.NameObjectKeysEnumerator.get_Current() at Microsoft.Web.Redis.RedisUtility.GetNewItemsAsList(ChangeTrackingSessionStateItemCollection sessionItems) in C:\TeamCity\buildAgent\work\59b31e8e4035fd30\src\Shared\RedisUtility.cs:line 68 at Microsoft.Web.Redis.RedisConnectionWrapper.SetPrepare(ISessionStateItemCollection data, Int32 sessionTimeout, String[]& keyArgs, Object[]& valueArgs) in C:\TeamCity\buildAgent\work\59b31e8e4035fd30\src\RedisSessionStateProvider\RedisConnectionWrapper.cs:line 115 at Microsoft.Web.Redis.RedisConnectionWrapper.Set(ISessionStateItemCollection data, Int32 sessionTimeout) in C:\TeamCity\buildAgent\work\59b31e8e4035fd30\src\RedisSessionStateProvider\RedisConnectionWrapper.cs:line 133 at Microsoft.Web.Redis.RedisSessionStateProvider.<SetAndReleaseItemExclusiveAsync>d__25.MoveNext() in C:\TeamCity\buildAgent\work\59b31e8e4035fd30\src\RedisSessionStateProvider\RedisSessionStateProvider.cs:`

This only happens for a monitoring bot:
UserAgent: Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)
Client-IP: 208.115.199.24

But it happens regularly, and I cannot see why.

NuGet packages is v4.0.1

**Comment by DarthSonic** [comment]
Not reproducible anymore.

**Comment by stanleysmall-microsoft** [comment]
Closing this issue as the context is not reproducible
