### ISSUE TITLE
When is the next release

### ISSUE THREAD

**Issue by kadamgreene** [Azure/aspnet-redis-providers#173]
I noticed that the last official release of this package was from 2018.  But we are facing a race condition with this package, in a class that no longer exists in master branch.  So... when is the next release of this package?

**Comment by toneill818** [comment]
@stanleysmall-microsoft Are there plans to create new releases for this package? It seems to be actively developed but the nuget package is outdated.

**Comment by stanleysmall-microsoft** [comment]
@kadamgreene, @toneill818, @hoerup, @areed829, @david-harrison-tyler, and @DaveyWood
A new version of these packages has been released: https://www.nuget.org/profiles/azurecache

**Comment by hoerup** [comment]
Changelog ?

**Comment by DaleyKD** [comment]
@stanleysmall-microsoft : How is it not backwards compatible?

**Comment by stanleysmall-microsoft** [comment]
@DaleyKD The serialization format changed (to primarily treat the SessionState and OutputCache entries as atomic units). If you try to read previous entries in Redis, the deserialization will fail. Currently we do not plan to offer a migration solution and suggest customers start with a fresh cache instance.

**Comment by DarthSonic** [comment]
@stanleysmall-microsoft what is the replacement for Microsoft.Web.Redis.ISerializer? How can we alter the serialization now? If we could use our ISerializer implementation further this would be no breaking change at all. Or do I miss something?

**Comment by stanleysmall-microsoft** [comment]
Hi @DarthSonic
The updated library removes the ability for users to customize the serialization method. We now use the provided serialization methods:
https://learn.microsoft.com/en-us/dotnet/api/system.web.sessionstate.sessionstateitemcollection.serialize
https://learn.microsoft.com/en-us/dotnet/api/system.web.sessionstate.sessionstateitemcollection.deserialize
