### ISSUE TITLE
Null reference exceptions if you store objects in the session that require HttpContext.Current in their constructors

### ISSUE THREAD

**Issue by stephenhaney-jta** [Azure/aspnet-redis-providers#18]
Hi all –

We were attempting to place some older classes to the session using this provider and hitting null reference exceptions when our classes would reconstruct during deserialization.

We discovered that:
1) These classes look for values in HttpContext.Current.Items in their constructors
2) HttpContext is not thread-safe
3) Deserialization (and reconstruction) takes place in a new thread where HttpContext.Current is null

The temporary fix:
We noticed thatRedisSessionStateProvider already passes around the "true" HttpContext between its own methods, but never sets the new thread's HttpContext.Current to the passed around reference.

In RedisSessionStateProvider.GetItemFromSessionStore, we set HttpContext.Current = context (context being the reference that's passed in to GetItemFromSessionStore). Our classes can than happily re-instantiate as they find the values where they expect them.

I'm not sure if that's the best solution overall. Does it make sense to set the HttpContext.Current at all in a new thread? Perhaps there's a better way to achieve this. I imagine we want to document this issue though for future users who may need to store legacy classes in the session.

Let me know if you have any questions or repro steps. Thanks.

**Comment by stephenhaney-jta** [comment]
Just creating a new notification that I've heavily updated this issue after finding a solution.

**Comment by sonjz** [comment]
+1
We also had issues with older classes placed in session.  We are currently using Harbour.RedisSessionStateStore and unable to switch due to this issue.  We'd like to switch because this provider is more feature-rich (retry parameter in particular).

**Comment by stephenhaney-jta** [comment]
Hi Sonjz,

You can try the fork we made for our use which fixes the HttpContext issue:
https://github.com/dpelham-jta/aspnet-redis-providers

The downside is lack of updates: We created this in December-ish and it's 4 commits behind at this point.

**Comment by SiddharthChatrolaMs** [comment]
We had discussion with ASP.NET team about this and they said it is not a good idea to do this. As changing HttpContext can cause many other bugs and it might break ASP.NET.
