### ISSUE TITLE
Questions regarding v5 references

### ISSUE THREAD

**Issue by DaleyKD** [Azure/aspnet-redis-providers#183]
I'm running an ASP .NET Framework=v4.8 web app.

Just upgraded to v5, and I have a few questions.
* Are all of these new references truly necessary (especially WindowsBase and ORACLE)?
  * System.Configuration.ConfigurationManager
  * System.Data.OracleClient !?
  * System.Security.AccessControl
  * System.Security.Permissions
  * System.Security.Principal.Windows
  * System.ServiceProcess
  * System.Transactions
  * WindowsBase
* Why is the assembly version 1.1.0.0 when the older one was 4.0.1.0?
* Why is the public key token gone?
* Why was there no modification to the web.config, specifically binding redirects?
* Your NuGet package description is just "Package Description."

**Comment by DarthSonic** [comment]
And where are the Release Notes? ;-)

**Comment by DaleyKD** [comment]
@DarthSonic : This is the closest we have right now: https://github.com/Azure/aspnet-redis-providers/issues/173#issuecomment-1458336706

For now, I am NOT installing this version. I think the stuff I posted above plus the breaking change in the release notes is sufficient reason.

**Comment by stanleysmall-microsoft** [comment]
Thanks for bringing these issues to our attention @DaleyKD 

Where are you seeing references to `System.Data.OracleClient` and `WindowsBase`? I'm not seeing references to these in the repository or in the [dependencies](https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider#dependencies-body-tab).

**Comment by DaleyKD** [comment]
@stanleysmall-microsoft : I've moved on to different projects right now, so I don't have time to track down the dependency tree (I'm sorry).

However, I JUST did this:
* In Visual Studio 2022, create a brand new ASP.NET Web Application (.NET Framework)
  * I selected .NET Framework 4.8 and Empty
  * ![image](https://github.com/Azure/aspnet-redis-providers/assets/7206282/e6b9372f-debb-4aff-911e-f8b03e339815)
* Add a NuGet Package
* Select Microsoft.Web.RedisSessionStateProvider
* Click Install
* Notice the two mentioned dependencies
* ![image](https://github.com/Azure/aspnet-redis-providers/assets/7206282/b373395f-c706-4564-87a5-f52f79c9f99d)

**Comment by stanleysmall-microsoft** [comment]
Apologies for the delayed response. `WindowsBase` and `System.Data.OracleClient` are transitive dependencies of the `System.Security.Permissions` package. This package is necessary to use the Session State Provider and I would encourage you to follow up with the maintainers of the `System.Security.Permissions` if these transitive dependencies cause concern.
