### ISSUE TITLE
v5 error - Microsoft.Bcl.AsyncInterfaces versions dont line up

### ISSUE THREAD

**Issue by PedrowPietrow** [Azure/aspnet-redis-providers#184]
Hello,

I am getting the following error on v5:
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0

Looking at the project dependency tree it looks like RedisSessionStateProvider installs Microsoft.Bcl.AsyncInterfaces.6.0.0 but StackExchange.Redis needs Microsoft.Bcl.AsyncInterfaces.5.0.0

**Comment by SimonS1988** [comment]
The same happened to me.
