### ISSUE TITLE
v5 - Microsoft.Web.Redis.ISerializer is not available any more

### ISSUE THREAD

**Issue by DarthSonic** [Azure/aspnet-redis-providers#185]
As for v5 Microsoft.Web.Redis.ISerializer is not available any more, now how to implement custom Serializer?

**Comment by jdivy** [comment]
What in the world is going on.  It's right here in the documentation as a feature (and we couldn't live without it)  https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-aspnet-session-state-provider

**Comment by DarthSonic** [comment]
Is there any possibility to get a reaction by the devs? Will this feature be re-implemented? And when?

**Comment by stanleysmall-microsoft** [comment]
@DarthSonic Versions 5.0.0 and onward do not allow users to customize the serialization method as we use the one provided in ASP.NET

@jdivy I will leave this issue open until the official documentation is updated. With version 5.0.0 existing as a breaking change, our documentation should reflect this.

**Comment by faraazaamir** [comment]
> @DarthSonic Versions 5.0.0 and onward do not allow users to customize the serialization method as we use the one provided in ASP.NET
> 
> @jdivy I will leave this issue open until the official documentation is updated. With version 5.0.0 existing as a breaking change, our documentation should reflect this.

@stanleysmall-microsoft Could you please advise why v5.0.0 does not allow to customize the serialization method? This was tremendously helpful as we could implement this interface to use JsonSerialization without us having to tag C# classes with [Serializable] attributes.
I believe this interface should be kept in newer versions as well.

**Comment by stanleysmall-microsoft** [comment]
@faraazaamir Customized serialization was removed because of deserialization risks in use of BinaryFormatter: https://learn.microsoft.com/dotnet/standard/serialization/binaryformatter-security-guide

We are not permitted to release any new code using the BinaryFormatter class. Instead, we chose to use the built-in serialization methods provided by the SessionStateItemCollection class https://learn.microsoft.com/dotnet/api/system.web.sessionstate.sessionstateitemcollection.serialize

**Comment by joaorosado** [comment]
> We are not permitted to release any new code using the BinaryFormatter class. Instead, we chose to use the built-in serialization methods provided by the SessionStateItemCollection class https://learn.microsoft.com/dotnet/api/system.web.sessionstate.sessionstateitemcollection.serialize

How does this help on making it more secure since SessionStateItemCollection.Serialize does still uses BinaryFormatter internally to serialize objects types inside the collection, while blocking the customizations to use formatters that were not vulnerable (like mentioned above, the JsonFormatters

**Comment by stanleysmall-microsoft** [comment]
@joaorosado 
[BinaryWriter](https://learn.microsoft.com/dotnet/api/system.io.binarywriter) "writes primitive types in binary to a stream" whereas [BinaryFormatter](https://learn.microsoft.com/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter) "serializes and deserializes an object, or an entire graph of connected objects, in binary format". In other words, BinaryWriter serializes/deserializes known primitive types and BinaryFormatter serializes/deserializes objects (which is unsafe). 

The team chose to utilize the [serialization methods provided by the SessionStateItemCollection class](https://learn.microsoft.com/en-us/dotnet/api/system.web.sessionstate.sessionstateitemcollection.serialize) to remove BinaryFormatter and provide similar functionality to other SessionState providers.

**Comment by faraazaamir** [comment]
@stanleysmall-microsoft , Could you please advise what workaround should we use now in order to avoid tagging all our PoCo classes with [Serializable] attributes, now that we cannot use ISerializer.
I guess upgrades should make things easier rather than difficult. I would try avoiding upgrade to v5.0.0 unless really needed.

**Comment by DarthSonic** [comment]
The problem is also that there can be properties that are not serializable and need to be declared as not serializable. But how should we find them all without running the code and forcing exceptions that currently do not hint why serialization fails. It is impossible to migrate to 5.0.0 currently. I declared over 50 classes serializable by searching the code for usage within session items but still cannot run the code because of 5.0.0 failing to serialize.

**Comment by joaorosado** [comment]
@stanleysmall-microsoft
I understand that it appears that way from what is said on the documentation pages, but it's not really the whole story.

SessionStateItemCollection.Serialize calls SessionStateItemCollection.WriteValueToStreamWithAssert to serialize each item
SessionStateItemCollection.WriteValueToStreamWithAssert then calls AltSerialization.WriteValueToStream
AltSerialization.WriteValueToStream of the value is an object calls BinaryFormatter.Serialize 
BinaryFormatter.Serializeand then, as you said, "serializes and deserializes an object, or an entire graph of connected objects, in binary format" 

So in the end it ends up with the exact same vulnerability, but having lost the capability of using a non-vulnerable serializer.
The only difference is that this project is not using the BinaryFormatter directly and instead hiding it on an indirection.

**Comment by ws-markb** [comment]
Unless I'm missing something obvious—and I freely admit I'm in no way an expert on this particular library—aren't the use of `BinaryFormatter` as a default and the ability to specify a custom serializer two completely separate issues?

I'm currently in a situation where I do need to use a different serializer, which doesn't use `BinaryFormatter` either. But in order to do so, I now either have to downgrade to an older version of this package, or fork the code and maintain my own version going forward. To me, both of those seem far less "secure" than just... allowing the serializer to be overridden?

I _absolutely_ understand the need to have secure defaults in place.... but completely removing the ability to customise them seems like a huge step backwards to me.

**Comment by murtymaganti** [comment]
Are there any other fixes in V5 outside the changes to serialization? I am thinking to use version 3.0.2 so I can use custom serialization but at same time want to make sure I don't run into any critical issues that are addressed in V5.

**Comment by stanleysmall-microsoft** [comment]
@murtymaganti I would recommend using version 4.0.1 if you wish to use customized serialization methods. The biggest difference between this version and the latest version is the serialization methods used.

**Comment by murtymaganti** [comment]
Hi @stanleysmall-microsoft thanks. I can use 4.0.1 but are there any known security risks using custom serialization? I ask this because it is removed in v5 and I guess there must be a strong reason for it.

**Comment by stanleysmall-microsoft** [comment]
@murtymaganti We are not permitted to release any new code containing the BinaryFormatter class. That is the primary reason for the change. Unfortunately, as @joaorosado mentions, the latest version also uses BinaryFormatter for non-primitive types. 

In either case, we're fundamentally using the same serialization method, but I had to remove references to BinaryFormatter to release a new version of the package.

**Comment by murtymaganti** [comment]
Maybe this is not right place to ask but has anyone compared the performance of using SQL database vs Redis for persisting sessions?

**Comment by stanleysmall-microsoft** [comment]
@murtymaganti 
I hope I can explain why we removed the ability to add custom serialization. When removing the existing serialization method (using Binaryformatter), we needed to replace the default serialization with some method. Using any other serialization (such as JSON serialization) would impose a storage structure where there was none before. We chose to use the serialization methods provided by the providers base class (which, _yes_, still use Binaryformater for non-primitive types). Using the existing methods offered the best compatibility because users can still serialize generic objects - where methods such as protobuf and json serialization require a contract definition. 

Please let me know if you agree @mgravell and @philon-msft 
Perhaps there exists a way we can still allow for customized serialization?

Adding @CawaMS for visibility

PS. Regarding the SQL question, you might look into cosmos: https://devblogs.microsoft.com/cosmosdb/asp-net-session-state-cache-provider/

**Comment by murtymaganti** [comment]
@stanleysmall-microsoft What happens when the session state provider loses connection to Redis server? Will it throw an exception and renders application unusable or will it create an empty session? What is the fallback handling?

**Comment by rvaidya-perfectserve** [comment]
Implementing a custom serializer allowed us to compress/decompress the data that we send to Redis before it is stored - the 5x implementation no longer allows this.

I mirror the sentiments, what has been said in this issue by the contributors does not explain why custom serialization was removed.  There are more use cases for implementing custom serialization than just BinarySerializer vs other message formats.

**Comment by DarthSonic** [comment]
> Implementing a custom serializer allowed us to compress/decompress the data that we send to Redis before it is stored - the 5x implementation no longer allows this.
> 
> I mirror the sentiments, what has been said in this issue by the contributors does not explain why custom serialization was removed. There are more use cases for implementing custom serialization than just BinarySerializer vs other message formats.

We did exactly the same. Using Gzip. It should be the coders choice which serializer to use with the MS preferred as default.

**Comment by code22live** [comment]
> As for v5 Microsoft.Web.Redis.ISerializer is not available any more, now how to implement custom Serializer?

Could you please share a code sample or share the library used to implement custom serializer (ISerializer) used with V4.0.1? We are migrating a legacy application and almost impossible to decorate all classes with [Serializable] attribute and ISerializer doesn't allow generics

**Comment by stanleysmall-microsoft** [comment]
@code22live here are some[ examples](https://github.com/search?q=Microsoft.Web.Redis.ISerializer+language%3AC%23&type=code&l=C%23)

**Comment by code22live** [comment]
> @code22live here are some[ examples](https://github.com/search?q=Microsoft.Web.Redis.ISerializer+language%3AC%23&type=code&l=C%23)

Thank you, much appreciated. 
Could you please give an idea whether the custom serializer option shall be added back in upcoming versions or not planned? Its a decision factor for the version to start with, if we build a custom serializer will we get stuck with 4.0.1 and unable to upgrade for future enhancements of the library,

**Comment by stanleysmall-microsoft** [comment]
@code22live 
There are currently no plans to add a custom serialization method to the library. If you need to use custom serialization, I recommend using v4.0.1

**Comment by DarthSonic** [comment]
> @code22live There are currently no plans to add a custom serialization method to the library. If you need to use custom serialization, I recommend using v4.0.1

This does not make any sense for me. You want to tighten security but do force users to still use (insecure) v4.0.1 because you removed an (IMHO) essential feature. You are saying "customized serialization was removed because of deserialization risks in use of BinaryFormatter" but in reality you do not gain any advantage in security if user still use v4.0.1.

So why not prevent usage of BinaryFormatter in another way be checking the custom serialization is not using BinaryFormatter on compile or runtime.

**Comment by code22live** [comment]
> > @code22live There are currently no plans to add a custom serialization method to the library. If you need to use custom serialization, I recommend using v4.0.1
> 
> This does not make any sense for me. You want to tighten security but do force users to still use (insecure) v4.0.1 because you removed an (IMHO) essential feature. You are saying "customized serialization was removed because of deserialization risks in use of BinaryFormatter" but in reality you do not gain any advantage in security if user still use v4.0.1.
> 
> So why not prevent usage of BinaryFormatter in another way be checking the custom serialization is not using BinaryFormatter on compile or runtime.


Totally agreed. It doesn't make sense to go with a lower version, if the interface and feature wont be restored in a future version. The only reason to consider a downgrade is if its temporary.

How can we request adding and expediting this feature, this being the library widely used and supported by MS?

**Comment by murtymaganti** [comment]
Now that the binary formatter is not used by this library anymore, anyone knows what happens to the sessionState service or SQL server providers? They both apparently use binary formatter to serialize. Is it safe to use them? Will they be discontinued?

**Comment by zachrybaker** [comment]
@murtymaganti the binary formatter is still in use, just implicitly.  See above. This situation is poor. I expect better from MS.

As I was already in the process of modifying this library for my case. Like @DarthSonic I really need custom serialization because I am going to read/write a shared session from both a web forms and Blazor app. The system web adaptors don't really support session for Blazor via the web adapters, and so I intend to pub-sub to these session objects in Redis as a synchronization mechanism.  I have implemented it, and I intend to share it back to the community.

4.0.1 is over five years stale, and there's been decent replumbing since then vs 5.0.3. So I just started with 5.0.3 and reintroduced a slightly different serializer, and also enabled a publish option. Both are optional, configurable.

**Comment by zachrybaker** [comment]
As promised.
[The PR](https://github.com/Azure/aspnet-redis-providers/pull/218)
[The commit](https://github.com/Azure/aspnet-redis-providers/pull/218/commits/c0e9294bd0f179deb25c6b0b03e80011abc7cf83)

Note that I am not fully versed in the intricacies of the net472 state enums, so while it's working fine for me, there might be an optimization I'm missing.

**Comment by faraazaamir** [comment]
@stanleysmall-microsoft @zachrybaker ,

Could you please confirm if the custom serializer option will be available in an upcoming version? 
Thanks much!

**Comment by zachrybaker** [comment]
@faraazaamir  To be honest I don't understand what they're up to. It seems to have lit a fire b/c I've seen Stanley and another person have actively been working with it making it more to their liking. I see their activity on it but don't seem to have any say on it.  I think it's all good though, and yes I think the custom serializer will be in the end result. I am unsure if they will unwind the publish feature, so I am unsure if I will use what they are producing or not.

**Comment by faraazaamir** [comment]
@zachrybaker Thanks for the update! Mush appreciated.

@stanleysmall-microsoft , Could you please provide any estimated timeline when we can have the custom serializer capability back again. Am still stuck on v4.0.1 due to this.

**Comment by stanleysmall-microsoft** [comment]
Hi everyone, I am currently away for the next few weeks but will continue working on this feature at the end of February.

If you have an immediate need, you could try to make the changes philon requested. Otherwise, I will likely create a new release in March.
________________________________

**Comment by code22live** [comment]
Hi @stanleysmall-microsoft - when do you expect to release this new version with custom serialization option?

**Comment by frankyjquintero** [comment]
[https://github.com/Azure/aspnet-redis-providers/pull/218](url) :D

**Comment by stanleysmall-microsoft** [comment]
We have decided not to fix this issue. Please see this comment for details: https://github.com/Azure/aspnet-redis-providers/pull/218#issuecomment-2253709764

**Comment by DarthSonic** [comment]
> We have decided not to fix this issue. Please see this comment for details: [#218 (comment)](https://github.com/Azure/aspnet-redis-providers/pull/218#issuecomment-2253709764)

That's crazy! You are forcing users to use an old insecure version. This cannot be the preferred way. This is incredible 🤬

**Comment by frankyjquintero** [comment]
"Will version 4.0.1 continue to receive security patches? This is crucial for projects that use this serializer, which relies on this interface to create it."
"This decision to remove the interface that allowed us to have our own serializer, I believe, was not very wise. There are projects in .NET Framework that depend on this for extensibility, such as session state."

**Comment by DarthSonic** [comment]
> That's crazy! You are forcing users to use an old insecure version. This cannot be the preferred way. This is incredible 🤬

@stanleysmall-microsoft 
What this means is, that everyone using custom serialization will stick to v4.0.1 and never update.

**Comment by JamesDSch** [comment]
This is really disappointing. We rely on custom serialization that has nothing to do with unsafe binary serialization. We will eventually move to ASP.NET Core, but there is so much .NET Framework code that must be migrated first. Will Microsoft commit to patching v4 of this library should any vulnerability be discovered?

**Comment by stanleysmall-microsoft** [comment]
@JamesDSch Due to limitations in our release process, we are unable to release any updates to version 4.

**Comment by ws-markb** [comment]
As far as I understand it:

- `v4` used `BinaryFormatter` as it's default serializer, which is now known to be insecure and (understandably) is no longer supported by Microsoft
- `v4` supported custom serialization, which meant you could fairly easily use something _other_ than `BinaryFormatter` to serialize your session data, and many of us in this thread did that
- `v5` still uses `BinaryFormatter` under the hood anyway, so the default serialization is just as "insecure"... but somehow, it also now can't allow serializers which _don't_ use `BinaryFormatter` either—despite [a PR already being created which does just that](https://github.com/Azure/aspnet-redis-providers/pull/218)

So: the _only_ pathway that actually allows us _not_ to use `BinaryFormatter` has been completely and permanently removed from `v5`, and no further fixes or security updates will ever be released for `v4`.

I genuinely feel that I'm missing something fundamental here?

**Comment by DarthSonic** [comment]
This summary sums it up perfectly! That is the reason I labelled the whole thing "crazy" here.

**Comment by stanleysmall-microsoft** [comment]
@ws-markb Your understanding is correct.
