### ISSUE TITLE
ChangeTrackingSessionStateItemCollection.cs no se encontró

### ISSUE THREAD

**Issue by jlgg88** [Azure/aspnet-redis-providers#20]
I´m using Redis Session State Provider but when i debugging ocurrs the error

Looking source 'd:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\ChangeTrackingSessionStateItemCollection.cs'. Checksum: MD5 {9 f0 b2 17 4d 58 c2 a7 68 b7 2c 14 c1 5e 20 85}
File 'd:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\ChangeTrackingSessionStateItemCollection.cs' does not exist.
Searching 'd:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\ChangeTrackingSessionStateItemCollection.cs' at documents scripts...
Looking at projects 'd:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\ChangeTrackingSessionStateItemCollection.cs'.
The file was not found on a project.
Searching the directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\crt\src\'...
Searching the directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\crt\src\vccorlib\'...
Searching the directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\src\mfc\'...
Searching the directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\src\atl\'...
Searching the directory 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\atlmfc\include'...
Searching the directory 'C:\'...
The configuration file debugging source code for the active solution indicate that the debugger does not prompt the user to search the file: d:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\ChangeTrackingSessionStateItemCollection.cs.
The debugger can not find the source file 'd:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\ChangeTrackingSessionStateItemCollection.cs'.

**Comment by SiddharthChatrolaMs** [comment]
Need more details to debug this further.

**Comment by SiddharthChatrolaMs** [comment]
Closing this because of lake of information.
