### ISSUE TITLE
Support for DefaultAzureCredential / Azure Active Directory / Entra ID

### ISSUE THREAD

**Issue by GMacAussie** [Azure/aspnet-redis-providers#223]
With Redis Cache for Azure moving to Entra identities (in Preview) and the latest Microsoft.Azure.StackExchangeRedis package (3.0.0) supporting DefaultAzureCredential with StackExchange.Redis, is the session state package going to be updated for credential use (thus removing the security gap)?

EDIT: As we are moving forward on our side for our own internal usage of Redis using a singleton `IConnectionMultiplexer` (per https://github.com/StackExchange/StackExchange.Redis/blob/main/docs/Basics.md).

I do see a PR mentioning this for the DI case.

**Comment by PaulVrugt** [comment]
any update on this?

**Comment by stanleysmall-microsoft** [comment]
Hello, the team has decided not to add the feature of Entra ID to these packages. Please refer to this https://learn.microsoft.com/aspnet/core/performance/caching/overview for the .NET Core caching style. Usage of our providers is limited, and declining. We do not plan to make much future investment in this repository.

@GMacAussie @PaulVrugt

**Comment by PaulVrugt** [comment]
@stanleysmall-microsoft thanks for the info. Although this doesn't help us at all. The application in which we are using this is framework 4.8, and it'll take years for us to move everything to modern .net.

I think we're not the only ones stuck here. I'll consider creating a fork and adding support myself
