### ISSUE TITLE
How to do client configuration for connecting to Sentinel Servers

### ISSUE THREAD

**Issue by cjeganr** [Azure/aspnet-redis-providers#25]
Hi, 

We are planning to use Redis with Sentinal Setup. Does RedisSessionState Provider supports Sentinel. How do i need to configure my web.config to use the sentinel feature of Redis.

Please help.

Thank you

**Comment by SiddharthChatrolaMs** [comment]
You basically use connectionString parameter which is basically StackExchange.Redis connection string
