### ISSUE TITLE
Provide a custom/extensible serialization mechanism

### ISSUE THREAD

**Issue by pruiz** [Azure/aspnet-redis-providers#29]
The current serialization of data to/from redis is based on BinaryFormatter. However, having a custom/extensible mechanism allowing the user to provide/register it's own serializer would be a great addition to this component.

Would you guys be willing to accept some form of pull-request implementing this feature?

Regards

**Comment by thepirat000** [comment]
Agree with @pruiz, a custom serialization would be great.

**Comment by JonCole** [comment]
Seems like a very reasonable request.  Yes, we would accept a pull request for something like this...

**Comment by thepirat000** [comment]
Just created a pull request for this #38

**Comment by SiddharthChatrolaMs** [comment]
Added few code review comments

**Comment by thepirat000** [comment]
Code changes were made and commited to the pull request accordingly to @SiddharthChatrolaMs  comments

**Comment by SiddharthChatrolaMs** [comment]
This is merged. I will release new NuGet package after some polishing of code and internal review.

**Comment by SiddharthChatrolaMs** [comment]
NuGet packages are out: 
https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/2.2.2
https://www.nuget.org/packages/Microsoft.Web.RedisOutputCacheProvider/1.7.2
