### ISSUE TITLE
Cannot add values to session after long-running async methods

### ISSUE THREAD

**Issue by bgmg** [Azure/aspnet-redis-providers#30]
I'm experiencing an issue with client side caching where I'm unable to add values to the session after long running async calls (180000 ms or more). When I remove the async call, I can add values again. Any suggestions?

**Comment by SiddharthChatrolaMs** [comment]
Please provide more details. If you can send a reproducible test app than that would be more helpful. It might be the case that app is hitting request timeout.

**Comment by SiddharthChatrolaMs** [comment]
Please reopen if when you have details.
