### ISSUE TITLE
Support multiple instances of RedisSessionStateProvider in an application

### ISSUE THREAD

**Issue by davidbending** [Azure/aspnet-redis-providers#35]
We'd like to have two instances of the RedisSessionStateProvider, so that we can place a replicating session state provider over the top.  We want to push writes through both providers and read from the primary.  The reason for this is to maintain session state caches in two Azure data centers, so that when we flip front-ends between data centers customer's sessions aren't broken.
This currently isn't possible because the configuration object is static and therefore shared between all instances of the session provider.
Is there any reason why multiple providers couldn't be supported?  Or is there a better way to support our use case?

**Comment by SiddharthChatrolaMs** [comment]
We do have task in backlog for implementing GeoReplication in Azure Redis Cache, which should be available in next few months. Once that is available Azure Redis Cache will do this so we do not have plan to implement it inside Redis Session State Provider.

**Comment by itabas016** [comment]
I have a almost same question, I have two server, one is primary, the other is slave and backup. when master is down, I want to upgrade the secondary to master immediately and make a swap. so this is my requirement.
I want use the redis sentinel function in my use case. If the latest version support multiple instances, when master is down and I switch on redis sentinel, redis server will automatic failover, but this provider how to be notified which one is the current new master?

**Comment by SiddharthChatrolaMs** [comment]
Sorry for late reply. Geo Replication is now available with Azure Redis Cache. 

https://azure.microsoft.com/en-us/blog/azure-redis-cache-geo-replication-in-public-preview/
https://docs.microsoft.com/en-us/azure/redis-cache/cache-how-to-geo-replication

I am closing this issue as resolved. If you need more information feel free to contact us

**Comment by JonCole** [comment]
As a followup on this issue, one thing to consider is that this session state provider is built on top of StackExchange.Redis, which can already be configured to support multiple Redis instances (e.g. master/slave).  We haven't directly tested this scenario, but you should be able to configure multiple Redis instances through the connectionString, then experiment to see if that functionality meets your needs.

**Comment by viperguynaz** [comment]
@JonCole how do you go about configuring the session state provider to support multiple Redis instances (master/slave)?

**Comment by JonCole** [comment]
If you are using Azure Redis, you just need to have a Standard/Premium tier cache.  Basic tier is single node.  If you are not on Azure Redis, then you can provide multiple endpoints to the [configuration string](https://github.com/Azure/aspnet-redis-providers/wiki/Configuration#connectionstring-valid-stackexchangeredis-connection-string-string).

**Comment by viperguynaz** [comment]
@JonCole thanks - I get how Redis is setup in Azure, but how are the session read/writes handled in the session provider?  You can't write to the slave and only 1 connection string is allowed (read/write).  So what am I missing? I don't see how the provider can be configured to write to the master, but read from the slave (same data center).

**Comment by JonCole** [comment]
@viperguynaz - a single connection string can take multiple endpoints in it.  The [Basic Configuration Strings section](https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Configuration.md#basic-configuration-strings) of the StackExchange.Redis docs has a simple example that lists two redis instances, comma separated.

@SiddharthChatrolaMs - can you answer the question about whether it is possible to read from slave while writing to master?
