### ISSUE TITLE
MOVED Exception

### ISSUE THREAD

**Issue by doterme** [Azure/aspnet-redis-providers#36]
i faced moved exception,what should i do...
![image](https://cloud.githubusercontent.com/assets/12495369/17122947/96ad0a00-5312-11e6-98d6-f8b891cba483.png)

**Comment by JonCole** [comment]
An explanation of what causes MOVED errors can be found here:  https://gist.github.com/hrishi18pathak/f10a6301239baae84fcf00eddcc5e5ea#file-redisclustererrors-md

**Comment by doterme** [comment]
i update StackExchang.Redis to StackExchange.Redis 1.1.603 (latest stable)	 from nuget,i also got MOVED exception

**Comment by JonCole** [comment]
Moving to StackExchange.Redis build 1.1.603 won't fix all of your MOVED errors, but will help avoid some of them.  As noted in the article I pointed to, these errors can happen as a result of a connection blip, patching the server, etc.  

As a side note, we are working on a pull request to StackExchange.Redis to make the error messages more clear as to what is really happening under the covers, but will not make all errors go away. As stated in the article:

"In general, the customer application should also be more resilient to some number of MOVED errors as it can occur during a failover or a network blip. The app could retry before failing or falling back to some other location."
