### ISSUE TITLE
RedisOutputCache - add gives super high expiration time.

### ISSUE THREAD

**Issue by noambergPB** [Azure/aspnet-redis-providers#39]
Calling RedisOutputCacheConnectionWrapper.Add with expire datetime
generates two commands
Set key value
pexpire key datetime_in_seconds (a very big number "251932173768370")

Calling RedisOutputCacheConnectionWrapper.Set
generates one command
psetex key time_span_milliseconds value - and the timespan is ok

RedisOutputCacheConnectionWrapper line 57 -> 
            object[] valueArgs = new object[] { RedisUtility.GetBytesFromObject(entry), expiryTime.TotalMilliseconds };

why does the timespan use the totalmilliseconds methos ?

as oppose to StackExchangeClientConnection line 253 
            TimeSpan timeSpanForExpiry = utcExpiry - DateTime.UtcNow;

**Comment by SiddharthChatrolaMs** [comment]
This should be fixed in https://www.nuget.org/packages/Microsoft.Web.RedisOutputCacheProvider/1.7.1.
