### ISSUE TITLE
Redis Cluster Support

### ISSUE THREAD

**Issue by dvinales** [Azure/aspnet-redis-providers#4]
Can you provide support for redis cluster? 
In the last version using a cluster in the connectionstring throw the exception: "Multi-key operations must involve a single slot; keys can use 'hash tags' to help this, i.e. '{/users/12345}/account' and '{/users/12345}/contacts' will always be in the same slot".
The solution is very simple...i think that only changing the format of the key solve the issue.

**Comment by JonCole** [comment]
We will take a look shortly.  Thanks for reporting this issue.

**Comment by SiddharthChatrolaMs** [comment]
https://github.com/Azure/aspnet-redis-providers/pull/5 
This pull request takes care of this. I will review and merge it ASAP.

**Comment by SiddharthChatrolaMs** [comment]
Following package supports clustering
https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/2.0.1-preview
