### ISSUE TITLE
Is Microsoft.Web.RedisSessionStateProvider got from nuget.org also under the MIT License ?

### ISSUE THREAD

**Issue by ganaware** [Azure/aspnet-redis-providers#40]
In the nuget.org page ( https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/ ),
there is a link to the license ( https://www.microsoft.com/web/webpi/eula/aspnetcomponent_rtw_enu.htm ).  But it is not the MIT License.

Is the license link in nuget.org page wrong?
Should it be linked to the MIT Liscense?

**Comment by SiddharthChatrolaMs** [comment]
This is normal behavior and nothing new. Source code once open sourced is usually under MIT License and most NuGet packages produced from it are usually under different license as dll's are signed by Microsoft. This is totally fine.

**Comment by ganaware** [comment]
Ok! Thank you for reply.
