### ISSUE TITLE
Task returning methods support with the OutputCache Providers - .NET 4.6.2

### ISSUE THREAD

**Issue by Beton** [Azure/aspnet-redis-providers#41]
As title says.
Any plans to release version that supports async methods introduced in .NET 4.6.2 ?

Thanks

**Comment by SiddharthChatrolaMs** [comment]
Please provide more details.

**Comment by wakm** [comment]
@Beton  Do you mean the new Async Improvments for SessionStateModule and Output-Cache (https://blogs.msdn.microsoft.com/dotnet/2016/08/02/announcing-net-framework-4-6-2/)? 

If yes, are there any plans to offer the redis-providers in a async version?

**Comment by Beton** [comment]
@wakm Yep I meant that.

**Comment by SiddharthChatrolaMs** [comment]
This is same as this: https://github.com/Azure/aspnet-redis-providers/issues/60

**Comment by SiddharthChatrolaMs** [comment]
Closing as duplicate
