### ISSUE TITLE
Ability to support reading from read replicas

### ISSUE THREAD

**Issue by seteam1** [Azure/aspnet-redis-providers#44]
Is there any current or future plans to support providing endpoints to target read replicas from a redis cluster?

Thanks!

**Comment by cadams93** [comment]
I am also interested in this - my application uses Redis Cluster with 6 nodes (three masters and three slaves) to serve session data. This kind of scaleout would normally increase read performance, but as far as I can tell, the RedisSessionStateProvider implementation demands a master to perform all operations.

As per @seteam1's comment, are there any plans to support reading from replicas (I would assume only when a write lock is not required)?

Thanks :)

**Comment by philipbjorge** [comment]
@cadams93 -- Can you expand on what you meant about write locks?

I was about to fork the library and add some flags here to support reading from slaves -- https://github.com/Azure/aspnet-redis-providers/blob/019c51b0a29dda9beb9d588edd20787804538df5/src/OutputCacheProvider/RedisOutputCacheConnectionWrapper.cs#L75

But is it not as easy as I think?

**Comment by cadams93** [comment]
@philipbjorge Thanks for taking an interest in this one :)

IIRC, an exclusive write lock is taken when SessionStateBehaviour.Required is set on the page/resource. To my knowledge, this does not prevent further reads on the same session, but would stop any further write clients from being able to access that session (writes are forced to be serial).

My concern is that one cannot simply add a DemandSlave/PreferSlave flag for a SessionStateBehaviour.Required resource, as it would not be able to write the value for the write-lock nor commit the changes on SessionState release. Therefore the flags would need to be altered based on the SessionStateBehaviour of the request.

**Comment by philipbjorge** [comment]
Ah I see... You are interested in this for sessions, and I'm interested in it for Output Cache...

**Comment by mapalan** [comment]
@cadams93 @philipbjorge, sorry for the incredibly long response time, I'm relatively new and the rest of our team hasn't had time to update the repo in quite a while. Is this still something you have an issue with and would like to see changed?

**Comment by carlcamilleri** [comment]
The original issue is linked to having a Master/Slave configuration of Redis (not a cluster). The load for session Redis calls is all routed to the master node, essentially having only the slaves for HA and not for scaling out. Is there any way to scale out read operations to Redis slaves ?

**Comment by philon-msft** [comment]
@carlcamilleri you can specify the `PreferReplica` flag on all read commands to load balance read traffic from primary to replica. More details here (note that `PreferSlave` has been renamed to `PreferReplica`): [How can I load balance reads on a master/slave redis setup?](https://stackoverflow.com/questions/52935434/how-can-i-load-balance-reads-on-a-master-slave-redis-setup)
