### ISSUE TITLE
Shared connection or connection string

### ISSUE THREAD

**Issue by yamaan608** [Azure/aspnet-redis-providers#45]
**Background** 
I have a web app that I am refactoring to use Redis session state.  I also have some other application state that I would like to use Redis for, and have created a basic implementation using StackExchange.Redis client.  I am also using a Sentinel-based architecture to provide master-slave failover, so there are multiple hosts listed in the connection string.

**Problem**
I don't want to have to define the connection string in two places, I want to get hold of either the connection string from the Redis session state provider, or maybe even better, get hold of the underlying Redis connection.
I notice the OutputCache provider does not have a ConnectionString configuration property, so is that not inconsistent with the Session state provider?

**Workarounds?**
Read the session state provider config to obtain the connectionstring value.
I don't think this is a particularly great solution.

**Possible solutions?**  
a) the provider exposes a public method to get the underlying StackExchange.Redis connection
b) the provider has an additional configuration attribute (eg connectionStringName), which is the name of a connection string in the usual <ConnectionStrings> configuration element.

**Comment by satheesh-krishnasamy** [comment]
I also have the same/similar requirement. I want to pass the connection string via connectionStringName. Since Azure powershell commandlet does not offer a way to update the connection string of the session state provider section (in web.config file). Currently we depend on the XSLT web config transformation which exposes the prod connection strings to all.

**Comment by JonCole** [comment]
The provider already has a mechanism for providing a connection string through appSettings or through a class/method you define in your own assembly.  I would think this should enable you to accomplish what you are looking for.

See https://github.com/Azure/aspnet-redis-providers/wiki/Configuration#how-to-use-configuration-parameters-of-session-state-provider-and-output-cache-provider for more details.  The class/method approach described is listed under "settingsClassName" and "settingsClassMethod"

If that will not work for your scenario, please provide details.

**Comment by satheesh-krishnasamy** [comment]
I got it.. The required feature is already implemented. I came to know after pulling the code branch. :)
