### ISSUE TITLE
RedisSessionStateProvider deserializes all session data up-front instead of when Session[key] invoked

### ISSUE THREAD

**Issue by digitalpacman** [Azure/aspnet-redis-providers#46]
Title really says it all.  I get serialization errors from a multi-application shared session state environment where not all session key value types exist in every application.  A and B types are in both apps, but C is only in the A app.  This works fine in other providers I've used because they rely on the built in deserialization behavior of SessionStateItemCollection.

The problem seems to be related to StackExchangeClientConnection.GetSessionData

The loop there invokes redisUtility.GetObjectFromBytes on every item which is a pass-through to serialization.

If you refer to the Microsoft.ApplicationServer.Caching.DataCacheSessionStoreProvider you can see how they handle this serialization so that the application doesn't fall down.  Upfront they store the byte[] format of the remote collection, and each item from the store is the start/end position of that object in a stream.  

The DataCacheSessionStoreProvider uses the SessionStateItemCollection.Deserialize() method and format for handling this.  You can either do that, or you can change the impl of your stored ISessionStateItemCollection.

SessionStateItemCollection.Deserialize is special because it stored the serialized ranges of the session collection in serialized format inside a private field.  Every time you access Session[key] it first checks to see if it's in the _serializedItems collection and is not deserialized, and deserializes it.  If you don't call that method it won't fill in that collection which forces you to handle the serialization. This should at least be a flag of some sort.

**Comment by SiddharthChatrolaMs** [comment]
This is fixed in session state provider release: https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/2.2.4. 
Look at release notes for more details: https://github.com/Azure/aspnet-redis-providers/wiki/Release-Notes
