### ISSUE TITLE
More flexible key naming

### ISSUE THREAD

**Issue by shahnhogan** [Azure/aspnet-redis-providers#49]
Would you be open to me submitting a pull request to allow for a more flexible KeyGenerator? Essentially,  I would like to have more flexible key naming that would align with my company's naming convention.

**Comment by JonCole** [comment]
Yes, we would certainly be willing to consider it.  I suspect this would be an extensibility point similar to the [ISerializer functionality recently added](https://github.com/Azure/aspnet-redis-providers/blob/master/src/Shared/ISerializer.cs) with a default implementation consistent with the current behavior.

**Comment by shahnhogan** [comment]
Great, thanks for being open to this, I'll look into it.

**Comment by JonCole** [comment]
Closing this issue for now.  Your PR will create a new issue.
