### ISSUE TITLE
SerializationException: The ObjectManager found an invalid number of fixups.

### ISSUE THREAD

**Issue by jordanchang** [Azure/aspnet-redis-providers#57]
[SerializationException: The ObjectManager found an invalid number of fixups. This usually indicates a problem in the Formatter.]

[SerializationException: The ObjectManager found an invalid number of fixups. This usually indicates a problem in the Formatter.]
   System.Runtime.Serialization.ObjectManager.DoFixups() +14053613
   System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage) +194
   System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage) +285
   Microsoft.Web.Redis.BinarySerializer.Deserialize(Byte[] data) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\BinarySerializer.cs:39
   Microsoft.Web.Redis.StackExchangeClientConnection.GetSessionData(Object rowDataFromRedis) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\StackExchangeClientConnection.cs:235
   Microsoft.Web.Redis.RedisConnectionWrapper.TryTakeWriteLockAndGetData(DateTime lockTime, Int32 lockTimeout, Object& lockId, ISessionStateItemCollection& data, Int32& sessionTimeout) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\RedisSessionStateProvider\RedisConnectionWrapper.cs:196
   Microsoft.Web.Redis.RedisSessionStateProvider.GetItemFromSessionStore(Boolean isWriteLockRequired, HttpContext context, String id, Boolean& locked, TimeSpan& lockAge, Object& lockId, SessionStateActions& actions) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\RedisSessionStateProvider\RedisSessionStateProvider.cs:276
   Microsoft.Web.Redis.RedisSessionStateProvider.GetItemExclusive(HttpContext context, String id, Boolean& locked, TimeSpan& lockAge, Object& lockId, SessionStateActions& actions) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\RedisSessionStateProvider\RedisSessionStateProvider.cs:190
   System.Web.SessionState.SessionStateModule.GetSessionStateItem() +176
   System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData) +980
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +636
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +137

Does anyone know what this means? Is it a limitation with the way serialization works?

**Comment by SiddharthChatrolaMs** [comment]
Redis session state uses "BinaryFormatter" to serialize session data. If you are trying to put something inside session that is not serializable by it then it will throw this kind of exception.

**Comment by JonCole** [comment]
A quick search of the web shows that this happens when the object you serialized previously is changed in a newer version of your app.  For example, changing the namespace on an object can lead to this issue.

**Comment by SiddharthChatrolaMs** [comment]
You can also use customer deserialization as described here: https://github.com/Azure/aspnet-redis-providers/wiki/Configuration#redisserializertype-string
