### ISSUE TITLE
Session.Abandon() does not close underlying connection to redis

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [Azure/aspnet-redis-providers#58]
I have an web app where terminal-sharing is a common case. When i user logs out I HttpSession.Abandon(), but the underlying connection to redis does not close, so when another user logs in, another connection get's up... and if the previous user gets back, the connection is not re-used, and yet another one is freshly provided...

**Comment by SiddharthChatrolaMs** [comment]
Redis session state provider creates a single StackExchange.Redis ConnectionMutiplexer and shares it among all calls. HttpSession.Abandon() will remove the session from Redis Cache but it won't have any effect on closing and opening connection. we never close/reopen connection in session state provider.
