### ISSUE TITLE
defaultDatabase is no use?

### ISSUE THREAD

**Issue by coldicelion** [Azure/aspnet-redis-providers#62]
hi, i have a problem with [connectionString] , i think  [defaultDatabase ] attribute in [connectionString] is no use, aspnet-redis-providers still use [databaseId] to read the database.

**Comment by SiddharthChatrolaMs** [comment]
Yes, we are aware of that bug. We have already merged the fix in [repo](https://github.com/Azure/aspnet-redis-providers/pull/53). we will generate new NuGet package with fix in next week.

**Comment by SiddharthChatrolaMs** [comment]
This is available in following NuGet packages.
https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/2.2.3
https://www.nuget.org/packages/Microsoft.Web.RedisOutputCacheProvider/1.7.3
