### ISSUE TITLE
No way to truly disable session state for ApiController? SessionStateModule.BeginAcquireState is still called!

### ISSUE THREAD

**Issue by mms-** [Azure/aspnet-redis-providers#64]
Session state supposedly is disabled by default in MVC ApiController, indeed HttpContext.Current.Session is null, however in load testing I'm seeing these exceptions, which are expected, however they occur for requests that are on the API controller, seems to me BeginAcquireState should never even be called.

This is caught in Application_Error where the current request shows it's an ApiController request.

Seems that session state is only half disabled for ApiControllers and sliding expiration updates still occur? Will [SessionState(System.Web.SessionState.SessionStateBehavior.Disabled)] disable it fully?

Exception : System.TimeoutException: Timeout performing EVAL, inst: 0, mgr: Inactive, err: never, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: Teleport.WebUX_IN_0, serverEndpoint: Unspecified/testing.redis.cache.windows.net:6380, keyHashSlot: 3266, IOCP: (Busy=1,Free=999,Min=50,Max=1000), WORKER: (Busy=42,Free=32725,Min=50,Max=32767), Local-CPU: 100% (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md) at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) at Microsoft.Web.Redis.StackExchangeClientConnection.<>c__DisplayClass4.b__3() in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\StackExchangeClientConnection.cs:line 119 at Microsoft.Web.Redis.StackExchangeClientConnection.RetryForScriptNotFound(Func`1 redisOperation) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\StackExchangeClientConnection.cs:line 137 at Microsoft.Web.Redis.StackExchangeClientConnection.RetryLogic(Func`1 redisOperation) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\StackExchangeClientConnection.cs:line 161 at Microsoft.Web.Redis.StackExchangeClientConnection.Eval(String script, String[] keyArgs, Object[] valueArgs) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\Shared\StackExchangeClientConnection.cs:line 119 at Microsoft.Web.Redis.RedisConnectionWrapper.UpdateExpiryTime(Int32 timeToExpireInSeconds) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\RedisSessionStateProvider\RedisConnectionWrapper.cs:line 90 at Microsoft.Web.Redis.RedisSessionStateProvider.ResetItemTimeout(HttpContext context, String id) in d:\TeamCityBuildAgent\work\f55792526e6d9089\src\RedisSessionStateProvider\RedisSessionStateProvider.cs:line 298 at System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData) at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) TraceSource="w3wp.exe"

**Comment by mms-** [comment]
It's by design, 12 years on still not changed https://referencesource.microsoft.com/#System.Web/State/SessionStateModule.cs line 676

Hopefully .Net Core has more control over session, if you 'disable' session state it shouldn't talk to the provider, as mentioned in the source code it's not performant and causing us problems. Disabling session state completely is not an option at this time.

**Comment by JonCole** [comment]
Right, this seems like something that needs to be fixed at the framework layer.
