### ISSUE TITLE
RedisConnectionException that disappeared after app restart

### ISSUE THREAD

**Issue by adrianiftode** [Azure/aspnet-redis-providers#66]
We had the following error, that didn't occur anymore after we restarted the app.

> Exception information: 
>     Exception type: RedisConnectionException 
>     Exception message: It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. ConnectTimeout

The app wasn't functioning while we had this error.

Is there a possibility to fallback to InProc until this issue is fixed?

**Comment by JonCole** [comment]
I suspect you are running into this: https://github.com/StackExchange/StackExchange.Redis/issues/559.  We will consider ways to make this provider resilient to such issues.

**Comment by SiddharthChatrolaMs** [comment]
We have included code to do force reconnect when such scenario happens. Please try it out:  https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/2.2.6
