### ISSUE TITLE
How to write redis connectstring in c# code?

### ISSUE THREAD

**Issue by qinshimignyue** [Azure/aspnet-redis-providers#67]
<add name="MySessionStateStore"
           host = "127.0.0.1" [String]
        port = "" [number]
        accessKey = "" [String]
        ssl = "false" [true|false]
        throwOnError = "true" [true|false]
        retryTimeoutInMilliseconds = "0" [number]
        databaseId = "0" [number]
        applicationName = "" [String]
        connectionTimeoutInMilliseconds = "5000" [number]
        operationTimeoutInMilliseconds = "5000" [number]

.....

How to write redis connectstring in c# code?

**Comment by JonCole** [comment]
Questions about usage should be submitted on an appropriate forum like stackoverflow.com.  They should not be filed as issues against a project.
