### ISSUE TITLE
can MS make a unlocked session? can you answer it as soon as possible?

### ISSUE THREAD

**Issue by 564064202** [Azure/aspnet-redis-providers#68]
this is every important?
can you?

**Comment by JonCole** [comment]
@564064202 I believe you are asking for an API that you can call to release the lock for a given session.  Is that correct?

**Comment by 564064202** [comment]
A lot of people has this question about why there is locking of session in every request. 
We  need a no locks option. We found that locking sometimes leads to a cascading event were many servers end up waiting on the same session to unlock.

I just discovered that every request in an ASP.Net web application gets a Session lock at the beginning of a request, and then releases it at the end of the request!

In case the implications of this are lost on you, as it was for me at first, this basically means the following:

Anytime an ASP.Net webpage is taking a long time to load (maybe due to a slow database call or whatever), and the user decides they want to navigate to a different page because they are tired of waiting, THEY CAN'T! The ASP.Net session lock forces the new page request to wait until the original request has finished its painfully slow load. Arrrgh.
Anytime an UpdatePanel is loading slowly, and the user decides to navigate to a different page before the UpdatePanel has finished updating... THEY CAN'T! The ASP.net session lock forces the new page request to wait until the original request has finished its painfully slow load. Double Arrrgh!
So what are the options? So far I have come up with:

Implement a Custom SessionStateDataStore, which ASP.Net supports. I haven't found too many out there to copy, and it seems kind of high risk and easy to mess up.
Keep track of all requests in progress, and if a request comes in from the same user, cancel the original request. Seems kind of extreme, but it would work (I think).
Don't use Session! When I need some kind of state for the user, I could just use Cache instead, and key items on the authenticated username, or some such thing. Again seems kind of extreme.
I really can't believe that the ASP.Net Microsoft team would have left such a huge performance bottleneck in the framework at version 4.0! Am I missing something obvious? How hard would it be to use a ThreadSafe collection for the Session?

**Comment by 564064202** [comment]
@JonCole

**Comment by JonCole** [comment]
The way the question was phrased, it sounded like this was something else, thus the request for clarification.  There is already an issue (#21) tracking support for a lock-free solution.  We will continue the discussion on that thread rather than having multiple for the same topic.  Note that we have been in discussion with the ASP.NET team and about this topic and we will provide a path forward as soon as possible.
