### ISSUE TITLE
System.TimeoutException: Timeout performing EVAL, inst: 1, mgr: ExecuteSelect, err: never, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=21,Free=32746,Min=4,Max=32767), clientName

### ISSUE THREAD

**Issue by mesutcakir** [Azure/aspnet-redis-providers#70]
System.TimeoutException: Timeout performing EVAL, inst: 1, mgr: ExecuteSelect, err: never, queue: 0, qu: 0, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=21,Free=32746,Min=4,Max=32767), clientName

AWS Ec2, AWS Redis.

**Comment by JonCole** [comment]
You are hitting ThreadPool growth throttling as described here: 
https://gist.github.com/JonCole/db0e90bedeb3fc4823c2#burst-of-traffic

You may also want to read this: https://gist.github.com/JonCole/925630df72be1351b21440625ff2671f#file-redis-bestpractices-general-md
