### ISSUE TITLE
Why is it so slow compare to Harbour.RedisSessionStateProvider ? How to run diagnostic?

### ISSUE THREAD

**Issue by sanychsamara** [Azure/aspnet-redis-providers#73]
We decided to migrate to Microsoft.Web.RedisSessionStateProvider from Harbour.RedisSessionStateProvider and found out that website become very slow. 

NewRelic monitoring shows that some session "get" operations take up to 3 seconds... Any advise on how can we troubleshoot that? 

Thank you.

**Comment by mapalan** [comment]
Hi @sanychsamara. Apologies for the incredibly long response time, I'm relatively new and the rest of our team hasn't had time to update the repo in quite a while. Is there still a performance issue that you're seeing?

**Comment by mapalan** [comment]
Closing due to lack of feedback.
