### ISSUE TITLE
Microsoft.Web.RedisSessionStateProvider  not working

### ISSUE THREAD

**Issue by haripradhan** [Azure/aspnet-redis-providers#77]
I created a simple ASP.NET application with Microsoft.Web.RedisSessionStateProvider nuget package (v. 2.2.4) installed, and then tested it with local redis server. It didn't work :(. It uses in-memory session storage which is really strange.

However, I again created another ASP.NET application with Microsoft.Web.RedisSessionStateProviderEx nuget package (which then installs Microsoft.Web.RedisSessionStateProvider v.1.1.0.0), and it luckily worked.

I wonder if anyone has come across this problem?

I have attached the following zip files:
1.  Redis1.zip which has Microsoft.Web.RedisSessionStateProvider, and 
 2. Redis2.zip which has Microsoft.Web.RedisSessionStateProviderEx.

[Redis1.zip](https://github.com/Azure/aspnet-redis-providers/files/1166519/Redis1.zip)
[Redis2.zip](https://github.com/Azure/aspnet-redis-providers/files/1166520/Redis2.zip)

**Comment by SiddharthChatrolaMs** [comment]
is you local redis running on port other than 6379?

**Comment by haripradhan** [comment]
It is running on the default port which is 6379.

**Comment by mapalan** [comment]
Hi, is this still an issue you are having?

**Comment by mapalan** [comment]
The issue here is that the web.config in the first zip file did not include StackExchange.Redis.StrongName as a dependent assembly, whereas the second one did.
