### ISSUE TITLE
Provider throws InvalidOperationException at random timing

### ISSUE THREAD

**Issue by shibayan** [Azure/aspnet-redis-providers#80]
When reading / writing load is applied, the following error is output at random timing.

```
Exception information:

    Exception type: InvalidOperationException

    Exception message: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at Microsoft.Web.Redis.RedisUtility.AppendUpdatedOrNewItemsInList(ChangeTrackingSessionStateItemCollection sessionItems, List`1 list) in D:\BuildAgent\work\f55792526e6d9089\src\Shared\RedisUtility.cs:line 55
   at Microsoft.Web.Redis.RedisConnectionWrapper.TryUpdateIfLockIdMatchPrepare(Object lockId, ISessionStateItemCollection data, Int32 sessionTimeout, String[]& keyArgs, Object[]& valueArgs) in D:\BuildAgent\work\f55792526e6d9089\src\RedisSessionStateProvider\RedisConnectionWrapper.cs:line 326
   at Microsoft.Web.Redis.RedisConnectionWrapper.TryUpdateAndReleaseLockIfLockIdMatch(Object lockId, ISessionStateItemCollection data, Int32 sessionTimeout) in D:\BuildAgent\work\f55792526e6d9089\src\RedisSessionStateProvider\RedisConnectionWrapper.cs:line 353
   at Microsoft.Web.Redis.RedisSessionStateProvider.SetAndReleaseItemExclusive(HttpContext context, String id, SessionStateStoreData item, Object lockId, Boolean newItem) in D:\BuildAgent\work\f55792526e6d9089\src\RedisSessionStateProvider\RedisSessionStateProvider.cs:line 414
   at System.Web.SessionState.SessionStateModule.OnReleaseState(Object source, EventArgs eventArgs)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by SiddharthChatrolaMs** [comment]
Which version of NuGet package are you using?

**Comment by shibayan** [comment]
@SiddharthChatrolaMs I'm using Version 2.2.5.

**Comment by iPipelineMK** [comment]
Seeing this in 2.2.6 as well.

**Comment by JonCole** [comment]
@iPipelineMK and @shibayan,  Are either of you accessing the session from any threads other than the main request thread? For example, do you do async work that can complete on another where that thread accesses the session?

**Comment by shibayan** [comment]
@JonCole No. It is Legacy Web Forms applications, do not use async at all. But this application used a lot of sessions.

**Comment by JonCole** [comment]
@shibayan This error indicates that the object was modified by something while an enumerator was in use.  That means that either 1) some other thread is interacting with the session while you are iterating the objects in the session or 2) the code that is doing the iterating is editing the session in the middle of the loop.  

Do you queue work onto other threads using Threads directly or by using things like ThreadPool.QueueUserWorkItem?  Do you have any code modifies the collection (in a nested method call maybe) while you are iterating through the items?

**Comment by woric** [comment]
*1) some other thread is interacting with the session while you are
iterating the objects in the session *

Hey  @shibayan <https://github.com/shibayan>,

I read this and my immediate thought is maybe 2 requests from the same
session are being processed at the same time on different threads.*

May not be relevant, but just a thought.

Woric

* Remember that each HttpRquest is handled on its own thread from a thread
pool, so there is nothing to stop there being 2 parallel requests from the
same session, especially if there is long running code and/or AXD handlers
for JavaScript or image processing.

**Comment by shibayan** [comment]
@JonCole No, application code does not manipulate sessions from another thread.
Such as load testing or production environment, an exception was caused when a large amount request is processed.

@woric In my perception, if ASP.NET Session State does not use async provider, session read / write gets lock and runs in single thread.

**Comment by iPipelineMK** [comment]
@JonCole - yes we are reading session keys in parallel tasks.

**Comment by woric** [comment]
>>  if ASP.NET Session State does not use async provider, session read /
write gets lock and runs in single thread.

Yes, each request runs in a single thread.

What I meant was that if a client (i.e. a browser) makes a second
HttpRequest before the first request has finished, then you will, in
effect, have 2 threads accessing the same session as the 2 requests are
overlapping on the server. (i.e. overlapping requests)

*Why this jumped out at me*
I have seen similar exceptions in web based code about 15 years ago. On
that occasion it took us months to figure out, and the reason it took many
months was because we wrongly assumed our code always ran in a single
thread. We never considered the same code running on 2 threads at the same
time accessing the same session, but once we started thinking about
multiple overlapping requests we found the problem.

As I said before, I have no idea if your problem is related to overlapping
requests.... but you should keep the scenario in the back of your mind
whilst searching for the cause of the problem. If you end up suspecting the
errors are caused by overlapping requests, then extensive logging including
the start and end of the each request processing (and with the session id
on each log line) is required.

**Comment by JonCole** [comment]
@woric - thanks for the details - very helpful!

@iPipelineMK - It is a bad idea to access HttpContext or any of the related structures from background tasks.  See issue #48 which has similar issues and where I describe a response from the ASP.NET team about doing this type of stuff...

**Comment by SiddharthChatrolaMs** [comment]
@woric @shibayan @JonCole 

I think I have found the issue. RedisUtility.AppendUpdatedOrNewItemsInList is trying to get modified value and to do that it is iteration over ModifiedKeys and fetching the value of each such modified keys. 

Code to fetch value also touches the ModifiedKeys which causes this. I will try to fix this and release new package in next few days.

**Comment by SiddharthChatrolaMs** [comment]
I have fixed this bug in commit: https://github.com/Azure/aspnet-redis-providers/commit/256e8ff886eb9fb609c737874885da2e8e75f1ab. I will release new NuGet with this sometime in next week.

**Comment by SiddharthChatrolaMs** [comment]
Sorry for the delay in releasing this. Our processes changes which caused the delay. 
https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/3.0.1

**Comment by SiddharthChatrolaMs** [comment]
Please use https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/3.0.2. As 3.0.1 has dll signing issue
