### ISSUE TITLE
RedisSessionProvider brakes OWIN ExternalLoginInfo

### ISSUE THREAD

**Issue by conyg** [Azure/aspnet-redis-providers#81]
I had a working project that uses both RedisSessionProvider and Microsoft.AspNet.Identity.Owin.2.2.1
Until RedisSessionProvider 2.2.3 everything works good but if I update RedisSessionProvider to the 2.2.4 or higher version, the functionality is broken.. Calling AuthenticationManager.GetExternalLoginInfo() will return null.
I tried different fixes as per this article: https://stackoverflow.com/questions/40269783/authenticationmanager-getexternallogininfoasync-on-google-aspnet-mvc5-returns
ot his article: https://stackoverflow.com/questions/20737578/asp-net-sessionid-owin-cookies-do-not-send-to-browser
but nothing seems to work.

Then I start looking at the updates I made and found that moving back to RedisSessionProvider 2.2.3 will fix the issue.

**Comment by SiddharthChatrolaMs** [comment]
which version of .net you are using?

**Comment by conyg** [comment]
My project is using .net 4.6.1

**Comment by JonCole** [comment]
We have been unable to reproduce this issue.  Are you still seeing the issue?  Have you tried on the latest release of the session state provider?  Please re-open the issue once you have provided more details.
