### ISSUE TITLE
CachedVary entries never cleaned?

### ISSUE THREAD

**Issue by ZNS** [Azure/aspnet-redis-providers#83]
Hi.

Outputcache adds CachedVary entries that have an expire date set to DateTime.MaxValue. These seem to never be cleaned from the cache. How do you suggest to solve that?

**Comment by SiddharthChatrolaMs** [comment]
Can you explain with example what is the issue? Redis Output Cache provider is very simple. It just gets key value pare and expiry time from ASP.NET and stores it in Redis.

**Comment by ZNS** [comment]
Everytime an OutputCacheEntry object is set a CachedVary object is added with url path as key. At least if you've varied the outputcache in some way, like varByHeader="host". This CachedVary entry is added with an expire date set to "9999-12-31". So the OutputCacheEntry object is cleared since it probably has a quite limited expire date but the CachedVary object is never cleared.

Not sure how big of an issue this is. CachedVary objects will only be orphaned when a previously cached url path doesn't exist anymore. But if you have a website with a large number of urls that change alot it might be a problem.

**Comment by SiddharthChatrolaMs** [comment]
This is about how ASP.NET calls output cache provider. Output cache provider is very simple library that sets key value in Redis when ASP.NET request with expiry specified by it. If something is getting set with high expiry and needs to be cleared then call should initiate from ASP.NET. 

Does this logic works with any other provider?

**Comment by mapalan** [comment]
@ZNS apologies for the incredibly long response time, I'm relatively new and the rest of our team hasn't had time to update the repo in quite a while. Have you been able to figure out why this happens? Since this doesn't look like an issue with this provider, I am leaning towards closing this issue.
