### ISSUE TITLE
Override the connection mechanism for RedisStateProvider

### ISSUE THREAD

**Issue by rupendra-sharma** [Azure/aspnet-redis-providers#84]
Hi
We are using RedisSessionState provider in .net mvc. We need to get the Redis server IPs and credentials from the database before connecting with Redis so we can not write the Redis server details in web.config as mentioned in most of the documentation.
Is there any way we can override the default connection behavior with a piece of code to pass a C# method which can actually get the Redis server details from the database and can pass it to RedisSessionState provider for the connection?

**Comment by SiddharthChatrolaMs** [comment]
Yes, there is a way to do this. You can use settingsClassName [String]and settingsMethodName [String].

https://github.com/Azure/aspnet-redis-providers/wiki/Configuration#settingsclassname-string

**Comment by rupendra-sharma** [comment]
Hi @SiddharthChatrolaMs 
Thanks for your reply. It was really helpful. One more thing I want to ask, is there a way to set a fallback Session storage in case the Redis session state provider is down ( Redis is down ). I am not sure if I should open a new ticket for it?
Appreciate your help.

Thanks
Rupendra
