### ISSUE TITLE
SessionId is not unique

### ISSUE THREAD

**Issue by abylouis** [Azure/aspnet-redis-providers#86]
We are experiencing sporadic issues where the SessionId is not unique and redis session provider is getting information from a different session. Has any one seen this? It's Azure hosted web site with Azure Redis Cache.

**Comment by JonCole** [comment]
No, we haven't seen this, but the sessionId is provided by ASP.NET and is not generated in this provider's code base.  So, any issue with the sessionId not being unique would likely need to be investigated at the ASP.NET layer.
