### ISSUE TITLE
3.0 preview - Lock still present

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [Azure/aspnet-redis-providers#89]
Hey guys,
I was under the impression that the 3.0 version would be lock free... unfortunately i still get stuck on that write lock... perhaps i'm doing something wrong?

**Comment by SiddharthChatrolaMs** [comment]
By default 3.0.0 version is not lock free. You have to enable that feature by adding app setting parameter as suggested here: https://github.com/Azure/aspnet-redis-providers/wiki/Release-Notes#v300-preview
