### ISSUE TITLE
GetItemExclusive_RecordFound test asserts incorrect SPI behaviour

### ISSUE THREAD

**Issue by echobravopapa** [Azure/aspnet-redis-providers#90]
This tests appears to be exercising GetItemExclusive in a scenario where the record is retrieved successfully, which per the SPI the exclusive lock is obtained.  The test asserts that the record is retrieved and that the lock is false (not obtained) see snippet below:  

         
```
SessionStateStoreData sessionStateStoreData = sessionStateStore.GetItemExclusive(null, id, out locked, out lockAge, out lockId, out actions);
A.CallTo(() => mockCache.TryTakeWriteLockAndGetData(A<DateTime>.Ignored, 90, out mockLockId, out sessionData, out sessionTimeout)).MustHaveHappened();
Assert.Equal(true, Utility.CompareSessionStateStoreData(sessionStateStoreData, sssd));
Assert.Equal(false, locked) ;
```

@mmartell and I assert that the test should not pass as currently written and `locked` should equal `true`

Is there something we are missing?  What is the assertion to locked == false intended to test?

Thanks!

**Comment by JonCole** [comment]
@SiddharthChatrolaMs can you take a look please?

**Comment by SiddharthChatrolaMs** [comment]
I will look into this once get off from current task

**Comment by SiddharthChatrolaMs** [comment]
Test is doing what it is supposed to do. locked = true means record was locked by other request and this request should wait. locked = false means record was not locked so we are able to lock it and we can execute the request. For more details check this:  https://msdn.microsoft.com/en-us/library/system.web.sessionstate.sessionstatestoreproviderbase.getitemexclusive.aspx#Anchor_1
