### ISSUE TITLE
Why can`t I  connect successfully ?

### ISSUE THREAD

**Issue by Luolanjiao** [Azure/aspnet-redis-providers#92]
my config is :
`<add name="MySessionStateStore" type="Microsoft.Web.Redis.RedisSessionStateProvider" host="localhost" port="6379" accessKey="test123" applicationName="Test" databaseId="1"  />`,
use parameter "accessKey",It cannot efficient,But use connectionString that setted the parameter into ,it is efficient ,like this:
` <add name="MySessionStateStore" type="Microsoft.Web.Redis.RedisSessionStateProvider" connectionString="localhost:6379,password="test123" applicationName="Test" databaseId="1" />`
  why ? who can tall me,please!

**Comment by SiddharthChatrolaMs** [comment]
Please try 127.0.0.1 instead of localhost. I vaguely remember hitting similar issue years back.

**Comment by JonCole** [comment]
Closing out this old issue as there isn't enough info to debug further and also due to lack of recent updates.
