### ISSUE TITLE
.Net 4.7.1

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [Azure/aspnet-redis-providers#93]
Is the 3.0 preview working with 4.7.X? looking at the imp i'm looking at a bunch of code specific for 4.6.2...

**Comment by lsuarez5280** [comment]
Using the 3.0 preview successfully with 4.7.1 for the async provider pipeline.

**Comment by SiddharthChatrolaMs** [comment]
@Leonardo-Ferreira if you still have issue then please reopen this and send us a test app and we can take a look.
