### ISSUE TITLE
Duplicate calls to GetItemFromSessionStore

### ISSUE THREAD

**Issue by dmarlow** [Azure/aspnet-redis-providers#98]
Hello, I'm using version 2.2.6 and am seeing things like this:

![redis](https://user-images.githubusercontent.com/2000510/38904820-7b629cc0-4261-11e8-9914-90d1e9f39b9e.PNG)

I'm trying to figure out the "Untracked Application Code" (we're using Stackify for APM), but it looks to be framework code. (Using ASP.NET MVC 5.2.3) on .NET 4.6.2.

I'm not seeing anything egregious in code, so I'm wondering if anyone has seen anything like this before.

**Comment by dmarlow** [comment]
I've figured this out. It looks like it's related to this: https://github.com/Azure/aspnet-redis-providers/blob/master/src/RedisSessionStateProvider/RedisSessionStateProvider.cs#L238-L240

How can lock timeout be configured? I'd rather have things fail fast than page hang for a long time.

**Comment by SiddharthChatrolaMs** [comment]
Lock timeout is just your http request timeout.

**Comment by dmarlow** [comment]
Thanks! I figured out it was a locking issue.
